[package]
name = "nemoclaw-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nemoclaw-sdk = { path = "../nemoclaw-sdk" }
clap.workspace = true
ratatui.workspace = true
terminal_size.workspace = true
serde_json.workspace = true
serde-saphyr.workspace = true
tokio = { workspace = true, features = ["signal", "io-std", "io-util", "net"] }

tempfile.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[[bin]]
name = "nemoclaw"
path = "src/main.rs"

[lints]
workspace = true
