// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// TOML config support for agents whose manifest declares `format: toml`
// (langchain-deepagents-code stores /sandbox/.deepagents/config.toml).
//
// Regression for #6548: parseConfig had no TOML branch, so `config get` fell
// through to JSON.parse and died on the generated file's leading `# Generated
// by NemoClaw...` comment. The fixture below mirrors the exact document shape
// agents/langchain-deepagents-code/generate-config.ts writes: header comments,
// nested tables, a quoted table key, arrays, booleans, and an inline table.

import { afterEach, describe, expect, it, vi } from "vitest";

const clientModulePath = require.resolve("../adapters/openshell/client");
const registryModulePath = require.resolve("../state/registry");
const agentDefsModulePath = require.resolve("../agent/defs");
const configModulePath = require.resolve("./config");

type ConfigModule = {
  parseConfig: (raw: string, format: string) => Record<string, unknown>;
  serializeConfig?: (config: Record<string, unknown>, format: string) => string;
  composeSandboxConfigBody: (
    config: Record<string, unknown>,
    target: {
      agentName: string;
      configPath: string;
      configDir: string;
      format: string;
      configFile: string;
    },
  ) => string;
  configGet: (name: string, opts?: { key?: string; format?: string }) => void;
};

type CaptureResult = {
  status: number;
  signal: null;
  error?: undefined;
  stdout: string;
  output: string;
  stderr: string;
};

const client = require(clientModulePath) as {
  captureOpenshellCommand: (...args: unknown[]) => CaptureResult;
};
const registry = require(registryModulePath) as {
  getSandbox: (name: string) => unknown;
};
const agentDefs = require(agentDefsModulePath) as {
  loadAgent: (name: string) => unknown;
};
const realCapture = client.captureOpenshellCommand;
const realGetSandbox = registry.getSandbox;
const realLoadAgent = agentDefs.loadAgent;

const DCODE_TARGET = {
  agentName: "langchain-deepagents-code",
  configPath: "/sandbox/.deepagents/config.toml",
  configDir: "/sandbox/.deepagents",
  format: "toml",
  configFile: "config.toml",
};

// Mirrors the document written by agents/langchain-deepagents-code/generate-config.ts.
const DCODE_CONFIG_TOML = [
  "# Generated by NemoClaw. This file contains no provider secrets.",
  "# NemoClaw provider route: inference; upstream provider: nvidia-prod; API: openai-completions.",
  "",
  "[models]",
  'default = "openai:nvidia/nemotron-3-super-120b-a12b"',
  "",
  "[models.providers.openai]",
  'models = ["nvidia/nemotron-3-super-120b-a12b"]',
  'api_key_env = "DEEPAGENTS_CODE_OPENAI_API_KEY"',
  'base_url = "https://inference.local/v1"',
  "enabled = true",
  "",
  "[models.providers.openai.params]",
  "# NemoClaw-managed inference.local currently exposes Chat Completions.",
  "use_responses_api = false",
  "",
  '[models.providers.openai.params."nvidia/nemotron-3-ultra-550b-a55b"]',
  "extra_body = { chat_template_kwargs = { force_nonempty_content = true } }",
  "",
  "[update]",
  "check = false",
  "auto_update = false",
  "",
].join("\n");

function loadConfigModule(): ConfigModule {
  delete require.cache[configModulePath];
  return require(configModulePath) as ConfigModule;
}

function stubTomlSandboxRead(raw: string): void {
  client.captureOpenshellCommand = () => ({
    status: 0,
    signal: null,
    stdout: raw,
    output: raw,
    stderr: "",
  });
}

function stubDcodeAgentResolution(): void {
  registry.getSandbox = () => ({ name: "alpha", agent: "langchain-deepagents-code" });
  agentDefs.loadAgent = () => ({
    name: "langchain-deepagents-code",
    configPaths: { dir: "/sandbox/.deepagents", configFile: "config.toml", format: "toml" },
  });
}

function captureStdout(run: () => void): string {
  const chunks: string[] = [];
  const spy = vi.spyOn(console, "log").mockImplementation((...args: unknown[]) => {
    chunks.push(args.map((a) => (typeof a === "string" ? a : String(a))).join(" "));
  });
  try {
    run();
  } finally {
    spy.mockRestore();
  }
  return chunks.join("\n");
}

describe("TOML sandbox config parsing (#6548)", () => {
  afterEach(() => {
    client.captureOpenshellCommand = realCapture;
    registry.getSandbox = realGetSandbox;
    agentDefs.loadAgent = realLoadAgent;
    delete require.cache[configModulePath];
  });

  it("parses the generated dcode config.toml, including its leading comments", () => {
    const { parseConfig } = loadConfigModule();

    const parsed = parseConfig(DCODE_CONFIG_TOML, "toml") as {
      models: {
        default: string;
        providers: {
          openai: {
            models: string[];
            base_url: string;
            enabled: boolean;
            params: Record<string, unknown>;
          };
        };
      };
      update: { check: boolean; auto_update: boolean };
    };

    expect(parsed.models.default).toBe("openai:nvidia/nemotron-3-super-120b-a12b");
    expect(parsed.models.providers.openai.models).toEqual(["nvidia/nemotron-3-super-120b-a12b"]);
    expect(parsed.models.providers.openai.base_url).toBe("https://inference.local/v1");
    expect(parsed.models.providers.openai.enabled).toBe(true);
    expect(parsed.models.providers.openai.params).toMatchObject({
      use_responses_api: false,
      "nvidia/nemotron-3-ultra-550b-a55b": {
        extra_body: { chat_template_kwargs: { force_nonempty_content: true } },
      },
    });
    expect(parsed.update).toEqual({ check: false, auto_update: false });
  });

  it("rejects a TOML document whose root is not a table of config values", () => {
    const { parseConfig } = loadConfigModule();

    expect(() => parseConfig("not = valid = toml", "toml")).toThrow();
  });

  it("round-trips a TOML config through composeSandboxConfigBody without changing values", () => {
    const { composeSandboxConfigBody, parseConfig } = loadConfigModule();
    const original = parseConfig(DCODE_CONFIG_TOML, "toml");

    const written = composeSandboxConfigBody(original, DCODE_TARGET);
    const reparsed = parseConfig(written, "toml");

    // `config set` writes through this path; serializing a TOML agent's config
    // as anything but TOML would corrupt /sandbox/.deepagents/config.toml.
    expect(written.endsWith("\n")).toBe(true);
    expect(reparsed).toEqual(original);
  });

  it("prints the dcode config from config get instead of failing with a JSON parse error", () => {
    stubTomlSandboxRead(DCODE_CONFIG_TOML);
    stubDcodeAgentResolution();
    const { configGet } = loadConfigModule();

    const out = captureStdout(() => configGet("alpha"));

    // Default output format for a TOML agent falls back to JSON rendering.
    const printed = JSON.parse(out) as {
      models: { default: string };
      update: { check: boolean };
    };
    expect(printed.models.default).toBe("openai:nvidia/nemotron-3-super-120b-a12b");
    expect(printed.update.check).toBe(false);
  });

  it("extracts a --key dotpath from a TOML config", () => {
    stubTomlSandboxRead(DCODE_CONFIG_TOML);
    stubDcodeAgentResolution();
    const { configGet } = loadConfigModule();

    const out = captureStdout(() => configGet("alpha", { key: "models.default" }));

    expect(JSON.parse(out)).toBe("openai:nvidia/nemotron-3-super-120b-a12b");
  });
});
