// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { describe, expect, it } from "vitest";

const { parseConfig, serializeConfig } =
  require("./config-format") as typeof import("./config-format");

describe("sandbox config formats", () => {
  it("parses a comment-prefixed TOML config with nested tables (#6548)", () => {
    const parsed = parseConfig(
      [
        "# Generated by NemoClaw. Do not edit by hand.",
        "[models]",
        'default = "openai:nvidia/meta/llama-3.1-8b-instruct"',
        "[models.providers.openai]",
        'models = ["nvidia/meta/llama-3.1-8b-instruct"]',
        "enabled = true",
      ].join("\n"),
      "toml",
    );

    expect(parsed).toEqual({
      models: {
        default: "openai:nvidia/meta/llama-3.1-8b-instruct",
        providers: {
          openai: { models: ["nvidia/meta/llama-3.1-8b-instruct"], enabled: true },
        },
      },
    });
  });

  it("keeps JSON and YAML parsing behavior", () => {
    expect(parseConfig('{"model":{"id":"nemotron"}}', "json")).toEqual({
      model: { id: "nemotron" },
    });
    expect(parseConfig("model:\n  id: nemotron\n", "yaml")).toEqual({
      model: { id: "nemotron" },
    });
  });

  it("refuses to serialize TOML as another format", () => {
    expect(() => serializeConfig({ model: "nemotron" }, "toml")).toThrow(
      /config set is not supported for TOML-format agents/,
    );
  });
});
