# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "nemoclaw-authoring"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nemoclaw-sdk = { path = "../nemoclaw-sdk" }
getrandom.workspace = true
serde-saphyr.workspace = true
serde_json.workspace = true

[lints]
workspace = true
