// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { buildHermesManagedPolicy } from "../../../agents/hermes/config/managed-policy.ts";
import { readHermesBuildSettings } from "../../../agents/hermes/config/build-env.ts";

const migrator = path.join(
  import.meta.dirname,
  "../../../agents/hermes/migrate-dashboard-state.py",
);
// Generated by the schema-v3 policy before #11763, at fcce93c721e8.
const previousDefaults = {
  display: {
    compact: false,
    tool_progress: "all",
    interim_assistant_messages: true,
    show_reasoning: false,
    show_commentary: false,
  },
  session_reset: {
    mode: "both",
    at_hour: 4,
    idle_minutes: 1440,
    notify: true,
    notify_exclude_platforms: ["api_server", "webhook"],
    bg_process_max_age_hours: 24,
  },
  updates: { pre_update_backup: false, refresh_cua_driver: false },
  memory: { memory_enabled: true, user_profile_enabled: true },
  curator: {
    enabled: true,
    interval_hours: 168,
    min_idle_hours: 2,
    stale_after_days: 30,
    archive_after_days: 90,
    consolidate: false,
    prune_builtins: true,
    backup: { enabled: true, keep: 5 },
  },
  auxiliary: {
    curator: {
      provider: "auto",
      model: "",
      base_url: "",
      api_key: "",
      timeout: 600,
      extra_body: {},
    },
  },
};

function readDatabaseSnapshot(filename: string) {
  const fd = fs.openSync(filename, "r");
  try {
    return { inode: fs.fstatSync(fd).ino, bytes: fs.readFileSync(fd) };
  } finally {
    fs.closeSync(fd);
  }
}

function fixture() {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "hermes-retired-defaults-"));
  const home = path.join(directory, "home");
  const legacy = path.join(home, "dashboard-home");
  fs.mkdirSync(legacy, { recursive: true });
  const env = {
    NEMOCLAW_MODEL: "fixture-model",
    NEMOCLAW_INFERENCE_BASE_URL: "https://inference.local/v1",
    NEMOCLAW_INFERENCE_API: "openai-completions",
  };
  const policy = buildHermesManagedPolicy(readHermesBuildSettings(env), env);
  const policyPath = path.join(directory, "policy.json");
  fs.writeFileSync(policyPath, JSON.stringify(policy));
  const target = JSON.parse(JSON.stringify(policy.config));
  const source = { ...structuredClone(target), ...structuredClone(previousDefaults) };
  for (const platform of [
    "a2a",
    "bluebubbles",
    "buzz",
    "dingtalk",
    "discord",
    "email",
    "feishu",
    "google_chat",
    "homeassistant",
    "irc",
    "line",
    "matrix",
    "mattermost",
    "msgraph_webhook",
    "ntfy",
    "photon",
    "qqbot",
    "raft",
    "relay",
    "signal",
    "simplex",
    "slack",
    "sms",
    "teams",
    "telegram",
    "wecom",
    "wecom_callback",
    "weixin",
    "whatsapp",
    "whatsapp_cloud",
    "webhook",
    "yuanbao",
  ])
    source.platforms[platform] = { enabled: false };
  fs.writeFileSync(path.join(legacy, "memory.txt"), "keep this user memory\n");
  return {
    directory,
    home,
    legacy,
    source,
    target,
    writeConfig() {
      fs.writeFileSync(path.join(home, "config.yaml"), JSON.stringify(target));
      fs.writeFileSync(path.join(legacy, "config.yaml"), JSON.stringify(source));
    },
    run(extraEnv: NodeJS.ProcessEnv = {}) {
      return spawnSync(
        "python3",
        ["-I", migrator, "--hermes-dir", home, "--managed-policy", policyPath],
        { encoding: "utf8", timeout: 5000, env: { ...process.env, ...extraEnv } },
      );
    },
  };
}

describe("Hermes prior generated-default migration", () => {
  it("migrates prior generated defaults and user memory without replacing native configuration (#11763)", () => {
    const f = fixture();
    try {
      f.writeConfig();
      const result = f.run();
      expect(result.status, result.stderr).toBe(0);
      expect(fs.existsSync(f.legacy)).toBe(false);
      expect(fs.readFileSync(path.join(f.home, "memory.txt"), "utf8")).toBe(
        "keep this user memory\n",
      );
      expect(JSON.parse(fs.readFileSync(path.join(f.home, "config.yaml"), "utf8"))).toEqual(
        f.target,
      );
    } finally {
      fs.rmSync(f.directory, { recursive: true, force: true });
    }
  });

  // SQLite migration uses directory-relative /proc/self/fd paths in Linux images.
  it.skipIf(process.platform !== "linux")(
    "resumes an interrupted database migration without replacing published user data (#11763)",
    () => {
      const f = fixture();
      try {
        f.writeConfig();
        const runtime = path.join(f.home, "runtime");
        fs.mkdirSync(runtime);
        fs.symlinkSync("runtime/state.db", path.join(f.home, "state.db"));
        const sourceDatabase = path.join(f.legacy, "state.db");
        const publishedDatabase = path.join(runtime, "state.db");
        const record = path.join(runtime, ".nemoclaw-dashboard-state-migration.json");
        const seed = spawnSync(
          "python3",
          [
            "-I",
            "-c",
            [
              "import sqlite3, sys",
              "db = sqlite3.connect(sys.argv[1])",
              "db.execute('CREATE TABLE messages (content TEXT)')",
              "db.execute('INSERT INTO messages VALUES (?)', ('keep this conversation',))",
              "db.commit()",
              "db.close()",
            ].join("\n"),
            sourceDatabase,
          ],
          { encoding: "utf8", timeout: 5000 },
        );
        expect(seed.status, seed.stderr).toBe(0);
        const interrupted = f.run({
          NEMOCLAW_TEST_INTERRUPT_AFTER_DASHBOARD_STATE_PUBLICATION: "1",
        });
        expect(interrupted.status, interrupted.stderr).toBe(1);
        expect(interrupted.stderr).toContain("the legacy copy could not be retired");
        expect(fs.existsSync(sourceDatabase)).toBe(true);
        expect(fs.existsSync(record)).toBe(true);
        const published = readDatabaseSnapshot(publishedDatabase);
        const resumed = f.run();
        expect(resumed.status, resumed.stderr).toBe(0);
        expect(readDatabaseSnapshot(publishedDatabase)).toEqual(published);
        expect(fs.existsSync(f.legacy)).toBe(false);
        expect(fs.existsSync(record)).toBe(false);
        expect(fs.readdirSync(runtime)).toEqual(["state.db"]);
        const rows = spawnSync(
          "python3",
          [
            "-I",
            "-c",
            [
              "import json, sqlite3, sys",
              "with sqlite3.connect(sys.argv[1]) as db:",
              "    print(json.dumps(db.execute('SELECT content FROM messages').fetchall()))",
            ].join("\n"),
            publishedDatabase,
          ],
          { encoding: "utf8", timeout: 5000 },
        );
        expect(rows.status, rows.stderr).toBe(0);
        expect(JSON.parse(rows.stdout)).toEqual([["keep this conversation"]]);
        expect(fs.readFileSync(path.join(f.home, "memory.txt"), "utf8")).toBe(
          "keep this user memory\n",
        );
        expect(JSON.parse(fs.readFileSync(path.join(f.home, "config.yaml"), "utf8"))).toEqual(
          f.target,
        );
      } finally {
        fs.rmSync(f.directory, { recursive: true, force: true });
      }
    },
  );

  it.each([
    [
      "changed default",
      (f: ReturnType<typeof fixture>) => {
        f.source.display.show_reasoning = true;
      },
    ],
    [
      "unknown option",
      (f: ReturnType<typeof fixture>) => {
        Object.assign(f.source.display, { new_preference: true });
      },
    ],
    [
      "target preference",
      (f: ReturnType<typeof fixture>) => {
        f.target.display = { show_reasoning: true };
      },
    ],
    [
      "enabled adapter",
      (f: ReturnType<typeof fixture>) => {
        f.source.platforms.a2a.enabled = true;
      },
    ],
    [
      "unknown adapter",
      (f: ReturnType<typeof fixture>) => {
        f.source.platforms.future_adapter = { enabled: false };
      },
    ],
    [
      "changed route",
      (f: ReturnType<typeof fixture>) => {
        f.source.model.base_url = "https://different.example/v1";
      },
    ],
    [
      "numeric boolean",
      (f: ReturnType<typeof fixture>) => {
        f.source.display.compact = 0;
      },
    ],
    [
      "unknown version",
      (f: ReturnType<typeof fixture>) => {
        f.source._config_version = 34;
      },
    ],
  ] as const)(
    "preserves both homes for manual reconciliation of a %s (#11763)",
    (_change, customize) => {
      const f = fixture();
      try {
        customize(f);
        f.writeConfig();
        const result = f.run();
        expect(result.status).toBe(1);
        expect(fs.readFileSync(path.join(f.legacy, "memory.txt"), "utf8")).toBe(
          "keep this user memory\n",
        );
        expect(JSON.parse(fs.readFileSync(path.join(f.legacy, "config.yaml"), "utf8"))).toEqual(
          f.source,
        );
        expect(JSON.parse(fs.readFileSync(path.join(f.home, "config.yaml"), "utf8"))).toEqual(
          f.target,
        );
      } finally {
        fs.rmSync(f.directory, { recursive: true, force: true });
      }
    },
  );
});
