[workspace]
members = ["crates/nemoclaw-sdk", "crates/nemoclaw-provider", "crates/nemoclaw-e2e", "crates/nemoclaw-cli", "crates/nemoclaw-runtime", "crates/nemoclaw-build"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
license = "Apache-2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"

[workspace.dependencies]
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "sync"] }
tf-provider = { git = "https://github.com/aneoconsulting/tf-provider", rev = "d4d1501e5e35d7d8d18184a319192c3f775d25f3" }
tempfile = "3"
serde-saphyr = "1.2"
sha2 = "0.11"
sha1 = "0.11"
regex = "1"
url = "2"
ipnet = "2"
openshell-core = { git = "https://github.com/NVIDIA/OpenShell", rev = "d1155aa70042d3e2ee49dbfa15346b108b7c1d92", default-features = false }
tonic = { version = "0.14", features = ["tls-ring", "tls-native-roots"] }
prost = "0.14"
tonic-prost = "0.14"
tower = "0.5"
http = "1"
tokio-stream = { version = "0.1", features = ["net"] }
getrandom = "0.4"
process-wrap = { version = "10", features = ["tokio1"] }
tokio-util = { version = "0.7", features = ["rt"] }
clap = { version = "4", features = ["derive"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "stream"] }
futures-util = "0.3"
time = { version = "0.3", features = ["formatting", "parsing"] }
bollard = { version = "0.21.1", default-features = false, features = ["pipe"] }
tar = "0.4"
rustix = { version = "1", features = ["fs"] }
zip = { version = "8.6", default-features = false, features = ["deflate"] }
flate2 = "1.1"
