FROM node:22-slim

WORKDIR /app

COPY . .

ENV NODE_ENV=development

RUN npm install
RUN npm install -D @types/node

RUN npm install -g typescript

RUN tsc --version

RUN npm run build:cli

RUN npm link

ENTRYPOINT ["nemoclaw"]