// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import Ajv2020, { type AnySchema, type ValidateFunction } from "ajv/dist/2020.js";
import { parseDocument } from "yaml";

import catalogSchema from "../../managed-inference/schemas/catalog.schema.json" with {
  type: "json",
};
import presetSchema from "../../managed-inference/schemas/preset.schema.json" with { type: "json" };
import recipeSchema from "../../managed-inference/schemas/recipe.schema.json" with { type: "json" };
import * as adapterRegistryModule from "../../src/lib/inference/serving/adapter-registry.ts";
import * as catalogIntegrityModule from "../../src/lib/inference/serving/catalog-integrity.ts";
import type {
  CompiledManagedInferenceCatalog,
  ManagedInferenceFactRequirement,
  ManagedInferenceServingPreset,
  ManagedInferenceServingRecipe,
} from "../../src/lib/inference/serving/catalog-types.ts";
import * as catalogTypesModule from "../../src/lib/inference/serving/catalog-types.ts";

const compatibleAdapterRegistryModule = adapterRegistryModule as unknown as {
  default?: typeof adapterRegistryModule;
};
const {
  getManagedInferenceRecipeRegistrationError,
  getManagedInferenceTopologyQualificationDescriptor,
} = compatibleAdapterRegistryModule.default ?? adapterRegistryModule;
const compatibleCatalogIntegrityModule = catalogIntegrityModule as unknown as {
  default?: typeof catalogIntegrityModule;
};
const { canonicalManagedInferenceJson, managedInferenceDigest, managedInferenceTextDigest } =
  compatibleCatalogIntegrityModule.default ?? catalogIntegrityModule;
const compatibleCatalogTypesModule = catalogTypesModule as unknown as {
  default?: typeof catalogTypesModule;
};
const {
  isManagedInferenceMaterializerOwnedArgument,
  MANAGED_INFERENCE_CATALOG_COMPILER_VERSION,
  MANAGED_INFERENCE_CATALOG_SCHEMA_VERSION,
} = compatibleCatalogTypesModule.default ?? catalogTypesModule;

const REPOSITORY_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const SOURCE_DIRECTORIES = ["managed-inference/presets", "managed-inference/recipes"] as const;
const GENERATED_CATALOG_MODULE_PATH = "src/lib/inference/serving/generated/catalog.ts";
const RECIPE_SCHEMA_ID = recipeSchema.$id;
const PRESET_SCHEMA_ID = presetSchema.$id;
const SHA256 = /^sha256:[0-9a-f]{64}$/u;

export interface ManagedInferenceCatalogSource {
  readonly path: string;
  readonly contents: string;
}

export interface CompiledManagedInferenceCatalogResult {
  readonly catalog: CompiledManagedInferenceCatalog;
  readonly module: string;
}

export function renderManagedInferenceCatalogModule(
  catalog: CompiledManagedInferenceCatalog,
): string {
  return `// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Generated by scripts/managed-inference/compile-catalog.mts from managed-inference YAML.
// Do not edit this file directly.

import type { CompiledManagedInferenceCatalog } from "../catalog-types.js";

const generatedCatalog: CompiledManagedInferenceCatalog = ${JSON.stringify(catalog, null, 2)};

export default generatedCatalog;
`;
}

function compareStrings(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function validationError(label: string, validate: ValidateFunction): Error {
  const details = validate.errors
    ?.map((error) => `${error.instancePath || "/"} ${error.message ?? "is invalid"}`)
    .join("; ");
  return new Error(`${label} failed schema validation${details ? `: ${details}` : ""}`);
}

function parseYamlSource(source: ManagedInferenceCatalogSource): unknown {
  const document = parseDocument(source.contents, {
    schema: "core",
    strict: true,
    uniqueKeys: true,
  });
  if (document.errors.length > 0) {
    throw new Error(
      `${source.path} is invalid YAML: ${document.errors[0]?.message ?? "parse failed"}`,
    );
  }
  try {
    return document.toJS({ maxAliasCount: 0 });
  } catch (error) {
    throw new Error(
      `${source.path} is invalid YAML: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

function createValidators(): {
  validateCatalog: ValidateFunction;
  validatePreset: ValidateFunction;
  validateRecipe: ValidateFunction;
} {
  const ajv = new Ajv2020({ allErrors: true, allowUnionTypes: true, strict: true });
  ajv.addSchema(recipeSchema as AnySchema);
  ajv.addSchema(presetSchema as AnySchema);
  const validateRecipe = ajv.getSchema(RECIPE_SCHEMA_ID);
  const validatePreset = ajv.getSchema(PRESET_SCHEMA_ID);
  if (!validateRecipe || !validatePreset) throw new Error("managed inference schemas did not load");
  return {
    validateCatalog: ajv.compile(catalogSchema as AnySchema),
    validatePreset,
    validateRecipe,
  };
}

function factRequirementError(requirement: ManagedInferenceFactRequirement): string | undefined {
  if (requirement.fact !== "cluster.nodeCount") {
    return "unsupported selection fact";
  }
  const { operator, value } = requirement;
  const arrayValue = Array.isArray(value) ? value : null;
  if (operator === "oneOf") {
    return arrayValue && arrayValue.length > 0
      ? undefined
      : "oneOf requires a non-empty value array";
  }
  if (operator === "between") {
    return arrayValue?.length === 2 && arrayValue.every((item) => typeof item === "number")
      ? undefined
      : "between requires exactly two numeric values";
  }
  if (arrayValue) return `${operator} requires one scalar value`;
  if ((operator === "atLeast" || operator === "atMost") && typeof value !== "number") {
    return `${operator} requires one numeric value`;
  }
  return undefined;
}

function validateRecipeSemantics(recipe: ManagedInferenceServingRecipe): void {
  if (!SHA256.test(recipe.spec.runtime.image.slice(recipe.spec.runtime.image.indexOf("@") + 1))) {
    throw new Error(`${recipe.metadata.id} must pin its runtime image by sha256 digest`);
  }
  if (!Object.hasOwn(recipe.spec.bindings, recipe.spec.execution.topologyBinding)) {
    throw new Error(
      `${recipe.metadata.id} references unknown topology binding ${recipe.spec.execution.topologyBinding}`,
    );
  }
  const seenArguments = new Set<string>();
  for (const argument of recipe.spec.serve.arguments) {
    if (seenArguments.has(argument.name)) {
      throw new Error(`${recipe.metadata.id} contains duplicate serving argument ${argument.name}`);
    }
    if (isManagedInferenceMaterializerOwnedArgument(argument.name)) {
      throw new Error(`${recipe.metadata.id} assigns materializer-owned argument ${argument.name}`);
    }
    seenArguments.add(argument.name);
  }
  const temporaryTargets = recipe.spec.runtime.temporaryFilesystems.map(({ target }) => target);
  if (new Set(temporaryTargets).size !== temporaryTargets.length) {
    throw new Error(`${recipe.metadata.id} contains duplicate temporary filesystem targets`);
  }
  for (const filesystem of recipe.spec.runtime.temporaryFilesystems) {
    const options = new Set(filesystem.options);
    if (
      (options.has("rw") && options.has("ro")) ||
      (options.has("exec") && options.has("noexec"))
    ) {
      throw new Error(`${recipe.metadata.id} contains conflicting temporary filesystem options`);
    }
  }
  const registrationError = getManagedInferenceRecipeRegistrationError(recipe);
  if (registrationError) {
    throw new Error(
      `${recipe.metadata.id} is incompatible with its registered adapters: ${registrationError}`,
    );
  }
}

function sortedKeys(value: object): string[] {
  return Object.keys(value).sort(compareStrings);
}

function validatePresetSemantics(
  preset: ManagedInferenceServingPreset,
  recipes: ReadonlyMap<string, ManagedInferenceServingRecipe>,
): void {
  const recipe = recipes.get(preset.spec.plan.recipeRef);
  if (!recipe) {
    throw new Error(
      `${preset.metadata.id} references unknown recipe ${preset.spec.plan.recipeRef}`,
    );
  }
  if (recipe.spec.backend !== preset.spec.plan.backend) {
    throw new Error(`${preset.metadata.id} backend does not match its recipe`);
  }

  const recipeBindingNames = sortedKeys(recipe.spec.bindings);
  const presetBindingNames = sortedKeys(preset.spec.plan.bindings);
  if (
    recipeBindingNames.length !== presetBindingNames.length ||
    recipeBindingNames.some((name, index) => name !== presetBindingNames[index])
  ) {
    throw new Error(`${preset.metadata.id} bindings do not exactly satisfy its recipe`);
  }
  const topologyRequirements = preset.spec.requirements.all
    .filter((requirement) => "topologyQualification" in requirement)
    .map(({ topologyQualification }) => topologyQualification);
  if (topologyRequirements.length !== recipeBindingNames.length) {
    throw new Error(
      `${preset.metadata.id} topology requirements do not exactly satisfy its recipe bindings`,
    );
  }
  for (const name of recipeBindingNames) {
    const recipeBinding = recipe.spec.bindings[name]!;
    const presetBinding = preset.spec.plan.bindings[name]!.valueFromTopologyQualification;
    const descriptor = getManagedInferenceTopologyQualificationDescriptor(
      recipeBinding.qualificationId,
      recipeBinding.schemaVersion,
    );
    if (
      !descriptor ||
      presetBinding.id !== recipeBinding.qualificationId ||
      presetBinding.schemaVersion !== recipeBinding.schemaVersion ||
      presetBinding.output !== descriptor.bindingOutput
    ) {
      throw new Error(`${preset.metadata.id} binding ${name} does not match its recipe`);
    }
    const matchingRequirements = topologyRequirements.filter(
      ({ id, schemaVersion, status }) =>
        id === presetBinding.id &&
        schemaVersion === presetBinding.schemaVersion &&
        status === "qualified",
    );
    if (matchingRequirements.length !== 1) {
      throw new Error(
        `${preset.metadata.id} binding ${name} requires one matching qualified topology requirement`,
      );
    }
  }
  for (const requirement of preset.spec.requirements.all) {
    if (!("fact" in requirement)) continue;
    const error = factRequirementError(requirement);
    if (error) throw new Error(`${preset.metadata.id} fact ${requirement.fact}: ${error}`);
    if (
      requirement.fact === "cluster.nodeCount" &&
      requirement.state === "present" &&
      requirement.operator === "equals" &&
      requirement.value !== recipe.spec.execution.nodeCount
    ) {
      throw new Error(`${preset.metadata.id} node-count requirement does not match its recipe`);
    }
  }
}

function assertUniqueDefinitionIds(
  presets: readonly { readonly definition: ManagedInferenceServingPreset }[],
  recipes: readonly { readonly definition: ManagedInferenceServingRecipe }[],
): void {
  const seen = new Map<string, string>();
  for (const [kind, definitions] of [
    ["preset", presets],
    ["recipe", recipes],
  ] as const) {
    for (const { definition } of definitions) {
      const existing = seen.get(definition.metadata.id);
      if (existing) {
        throw new Error(
          `managed inference definition ID ${definition.metadata.id} is duplicated by ${existing} and ${kind}`,
        );
      }
      seen.set(definition.metadata.id, kind);
    }
  }
}

function sortedJson(value: unknown): unknown {
  return JSON.parse(canonicalManagedInferenceJson(value));
}

export function compileManagedInferenceCatalogSources(
  sources: readonly ManagedInferenceCatalogSource[],
): CompiledManagedInferenceCatalogResult {
  const sortedSources = [...sources].sort((left, right) => compareStrings(left.path, right.path));
  if (new Set(sortedSources.map((source) => source.path)).size !== sortedSources.length) {
    throw new Error("managed inference catalog contains a duplicate source path");
  }
  const { validateCatalog, validatePreset, validateRecipe } = createValidators();
  const recipes: {
    definition: ManagedInferenceServingRecipe;
    definitionDigest: string;
    sourceFile: string;
  }[] = [];
  const presets: {
    definition: ManagedInferenceServingPreset;
    definitionDigest: string;
    sourceFile: string;
  }[] = [];

  for (const source of sortedSources) {
    if (!/^managed-inference\/(?:presets|recipes)\/[a-z0-9._-]+\.yaml$/u.test(source.path)) {
      throw new Error(`unsupported managed inference source path ${source.path}`);
    }
    const parsed = parseYamlSource(source);
    const kind =
      typeof parsed === "object" && parsed !== null
        ? (parsed as { readonly kind?: unknown }).kind
        : undefined;
    if (kind === "ServingRecipe") {
      if (!source.path.startsWith("managed-inference/recipes/") || !validateRecipe(parsed)) {
        throw validationError(source.path, validateRecipe);
      }
      recipes.push({
        definition: parsed as ManagedInferenceServingRecipe,
        definitionDigest: managedInferenceDigest(parsed),
        sourceFile: source.path,
      });
    } else if (kind === "ServingPreset") {
      if (!source.path.startsWith("managed-inference/presets/") || !validatePreset(parsed)) {
        throw validationError(source.path, validatePreset);
      }
      presets.push({
        definition: parsed as ManagedInferenceServingPreset,
        definitionDigest: managedInferenceDigest(parsed),
        sourceFile: source.path,
      });
    } else {
      throw new Error(`${source.path} has unsupported kind ${String(kind)}`);
    }
  }

  if (recipes.length === 0 || presets.length === 0) {
    throw new Error("managed inference catalog requires at least one recipe and one preset");
  }
  assertUniqueDefinitionIds(presets, recipes);
  for (const { definition } of recipes) validateRecipeSemantics(definition);
  const recipesById = new Map(
    recipes.map(({ definition }) => [definition.metadata.id, definition]),
  );
  for (const { definition } of presets) validatePresetSemantics(definition, recipesById);
  recipes.sort((left, right) =>
    compareStrings(left.definition.metadata.id, right.definition.metadata.id),
  );
  presets.sort((left, right) =>
    compareStrings(left.definition.metadata.id, right.definition.metadata.id),
  );

  const sourceFiles = sortedSources.map((source) => ({
    digest: managedInferenceTextDigest(source.contents),
    path: source.path,
  }));
  const withoutDigest = {
    compilerVersion: MANAGED_INFERENCE_CATALOG_COMPILER_VERSION,
    presets,
    recipes,
    schemaVersion: MANAGED_INFERENCE_CATALOG_SCHEMA_VERSION,
    sourceFiles,
    sourceRevision: managedInferenceDigest(sourceFiles),
  } as const;
  const catalog = sortedJson({
    ...withoutDigest,
    catalogDigest: managedInferenceDigest(withoutDigest),
  }) as CompiledManagedInferenceCatalog;
  if (!validateCatalog(catalog)) {
    throw validationError("compiled managed inference catalog", validateCatalog);
  }
  return {
    catalog,
    module: renderManagedInferenceCatalogModule(catalog),
  };
}

function readCatalogSources(repositoryRoot: string): ManagedInferenceCatalogSource[] {
  return SOURCE_DIRECTORIES.flatMap((directory) => {
    const absoluteDirectory = path.join(repositoryRoot, directory);
    return fs
      .readdirSync(absoluteDirectory, { withFileTypes: true })
      .filter((entry) => entry.isFile() && entry.name.endsWith(".yaml"))
      .map((entry) => {
        const sourcePath = `${directory}/${entry.name}`;
        return {
          path: sourcePath,
          contents: fs.readFileSync(path.join(repositoryRoot, sourcePath), "utf8"),
        };
      });
  });
}

export function compileManagedInferenceCatalog(
  repositoryRoot = REPOSITORY_ROOT,
): CompiledManagedInferenceCatalogResult {
  return compileManagedInferenceCatalogSources(readCatalogSources(repositoryRoot));
}

function main(): void {
  const unknownArguments = process.argv.slice(2).filter((argument) => argument !== "--write");
  if (unknownArguments.length > 0) throw new Error(`unknown argument ${unknownArguments[0]}`);
  const { module } = compileManagedInferenceCatalog();
  if (process.argv.includes("--write")) {
    const outputPath = path.join(REPOSITORY_ROOT, GENERATED_CATALOG_MODULE_PATH);
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, module, "utf8");
  }
}

if (fileURLToPath(import.meta.url) === path.resolve(process.argv[1] ?? "")) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
