[package]
name = "fabric-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "terraform-provider-fabric"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
nemoclaw-backend = { path = "../nemoclaw-backend" }
nemoclaw-docker = { path = "../nemoclaw-docker" }
nemoclaw-fabric = { path = "../nemoclaw-fabric" }
nemoclaw-openshell = { path = "../nemoclaw-openshell" }
nemoclaw-tofu = { path = "../nemoclaw-tofu" }
openshell-provider = { path = "../openshell-provider" }
nemo-fabric-core = { git = "https://github.com/NVIDIA/NeMo-Fabric", rev = "24f068c895e5cbc30286bc743498be4e5014d658" }
async-trait.workspace = true
regex.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error = "0.1"
tf-provider.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
nemoclaw-test-fixtures = { path = "../nemoclaw-test-fixtures" }
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
