[package]
name = "nemoclaw-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "nemoclaw-runtime"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
nemoclaw-sdk = { path = "../nemoclaw-sdk" }
tokio = { workspace = true, features = ["signal"] }
