[package]
name = "nemoclaw-e2e"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rcgen = "0.14.10"
rustls.workspace = true
nemoclaw-sdk = { path = "../nemoclaw-sdk" }
nemoclaw-provider = { path = "../nemoclaw-provider" }
async-trait.workspace = true
serde_json.workspace = true
serde.workspace = true
serde-saphyr.workspace = true
sha2.workspace = true
tf-provider.workspace = true
tokio.workspace = true
tempfile.workspace = true
openshell-core.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
prost.workspace = true
tower.workspace = true
http.workspace = true
tokio-stream.workspace = true

[[bin]]
name = "terraform-provider-nemoclaw-fixture"
path = "src/bin/provider.rs"

[lints]
workspace = true
