// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const DEEPAGENTS_MCP_MAX_SERVERS = 64;

export const DEEPAGENTS_STRICT_JSON_HELPERS = [
  "def reject_duplicate_keys(pairs):",
  "    result = {}",
  "    for key, value in pairs:",
  "        if key in result:",
  "            raise ValueError(f'duplicate JSON key: {key}')",
  "        result[key] = value",
  "    return result",
  "def reject_non_json_constant(value):",
  "    raise ValueError(f'non-JSON numeric constant: {value}')",
  "def strict_json_loads(raw):",
  "    return json.loads(raw, object_pairs_hook=reject_duplicate_keys, parse_constant=reject_non_json_constant)",
];

export const DEEPAGENTS_MANAGED_PROJECTION_READ_HELPERS = [
  "import errno",
  "MANAGED_MCP_MAX_BYTES = 262144",
  "def managed_projection_path_kind(mode):",
  "    if stat.S_ISLNK(mode):",
  "        return 'symbolic link'",
  "    if stat.S_ISFIFO(mode):",
  "        return 'FIFO'",
  "    if not stat.S_ISREG(mode):",
  "        return 'non-regular file'",
  "    return None",
  "def managed_parent_path_kind(mode):",
  "    if stat.S_ISLNK(mode):",
  "        return 'symbolic link'",
  "    if not stat.S_ISDIR(mode):",
  "        return 'non-directory parent'",
  "    return None",
  "def managed_fingerprint(metadata):",
  "    return (metadata.st_dev, metadata.st_ino, metadata.st_size, metadata.st_mtime_ns, metadata.st_ctime_ns, metadata.st_mode, metadata.st_nlink, metadata.st_uid)",
  "def managed_parent_fingerprint(metadata):",
  "    return (metadata.st_dev, metadata.st_ino, metadata.st_mode, metadata.st_uid)",
  "def raise_managed_parent_error(parent_descriptor, component, exc, unsafe_path_prefix=None):",
  "    unsafe_path_kind = None",
  "    try:",
  "        unsafe_path_kind = managed_parent_path_kind(os.stat(component, dir_fd=parent_descriptor, follow_symlinks=False).st_mode)",
  "    except OSError:",
  "        pass",
  "    if unsafe_path_kind and unsafe_path_prefix:",
  "        raise ValueError(f'{unsafe_path_prefix}: {unsafe_path_kind}') from exc",
  "    if unsafe_path_kind:",
  "        raise ValueError(f'managed MCP projection parent is a {unsafe_path_kind}') from exc",
  "    raise exc",
  "def open_managed_parent(path, create=False, unsafe_path_prefix=None):",
  "    if not path.is_absolute() or not path.name or path.name in ('.', '..'):",
  "        raise ValueError('managed MCP projection path must be absolute')",
  "    components = path.parts[1:-1]",
  "    descriptor = os.open('/', os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)",
  "    created = False",
  "    try:",
  "        for index, component in enumerate(components):",
  "            flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC | os.O_NOFOLLOW",
  "            try:",
  "                next_descriptor = os.open(component, flags, dir_fd=descriptor)",
  "            except FileNotFoundError:",
  "                if not create or index != len(components) - 1:",
  "                    raise",
  "                try:",
  "                    os.mkdir(component, 0o700, dir_fd=descriptor)",
  "                    created = True",
  "                except FileExistsError:",
  "                    pass",
  "                try:",
  "                    next_descriptor = os.open(component, flags, dir_fd=descriptor)",
  "                except OSError as exc:",
  "                    raise_managed_parent_error(descriptor, component, exc, unsafe_path_prefix)",
  "            except OSError as exc:",
  "                raise_managed_parent_error(descriptor, component, exc, unsafe_path_prefix)",
  "            os.close(descriptor)",
  "            descriptor = next_descriptor",
  "        metadata = os.fstat(descriptor)",
  "        if not stat.S_ISDIR(metadata.st_mode):",
  "            raise ValueError('managed MCP projection parent is not a directory')",
  "        return descriptor, managed_parent_fingerprint(metadata), created",
  "    except Exception:",
  "        os.close(descriptor)",
  "        raise",
  "def assert_managed_parent_stable(path, identity, unsafe_path_prefix=None):",
  "    try:",
  "        descriptor, current, _ = open_managed_parent(path, unsafe_path_prefix=unsafe_path_prefix)",
  "    except FileNotFoundError:",
  "        current = None",
  "        descriptor = None",
  "    try:",
  "        if current != identity:",
  "            raise ValueError('managed MCP projection parent changed during operation')",
  "    finally:",
  "        if descriptor is not None:",
  "            os.close(descriptor)",
  "def assert_managed_source_stable(entry_name, parent_descriptor, identity, unsafe_path_prefix=None):",
  "    try:",
  "        current_metadata = os.stat(entry_name, dir_fd=parent_descriptor, follow_symlinks=False)",
  "    except FileNotFoundError:",
  "        current_metadata = None",
  "    current = managed_fingerprint(current_metadata) if current_metadata is not None else None",
  "    if identity is None:",
  "        if current is not None:",
  "            unsafe_path_kind = managed_projection_path_kind(current_metadata.st_mode) if unsafe_path_prefix else None",
  "            if unsafe_path_kind:",
  "                raise ValueError(f'{unsafe_path_prefix}: {unsafe_path_kind}')",
  "            raise ValueError('managed MCP projection appeared during mutation')",
  "        return",
  "    if current != identity:",
  "        raise ValueError('managed MCP projection changed before mutation')",
  "def validate_managed_descriptor_path(entry_name, parent_descriptor, descriptor, unsafe_path_prefix=None):",
  "    opened = os.fstat(descriptor)",
  "    linked = os.stat(entry_name, dir_fd=parent_descriptor, follow_symlinks=False)",
  "    if unsafe_path_prefix:",
  "        unsafe_path_kind = managed_projection_path_kind(linked.st_mode)",
  "        if unsafe_path_kind:",
  "            raise ValueError(f'{unsafe_path_prefix}: {unsafe_path_kind}')",
  "    safe = (stat.S_ISREG(opened.st_mode) and opened.st_uid == os.getuid() and stat.S_IMODE(opened.st_mode) == 0o600 and opened.st_nlink == 1 and (opened.st_dev, opened.st_ino) == (linked.st_dev, linked.st_ino))",
  "    if not safe:",
  "        raise ValueError('managed MCP projection has unsafe ownership, mode, type, links, or path identity')",
  "    return managed_fingerprint(opened)",
  "def open_managed_projection(path, writable=False, unsafe_path_prefix=None):",
  "    try:",
  "        parent_descriptor, parent_identity, _ = open_managed_parent(path, unsafe_path_prefix=unsafe_path_prefix)",
  "    except FileNotFoundError:",
  "        return b'', None, None, None, None",
  "    entry_name = path.name",
  "    access = os.O_RDWR if writable else os.O_RDONLY",
  "    flags = access | os.O_CLOEXEC | os.O_NONBLOCK | os.O_NOFOLLOW",
  "    try:",
  "        try:",
  "            descriptor = os.open(entry_name, flags, dir_fd=parent_descriptor)",
  "        except FileNotFoundError:",
  "            assert_managed_source_stable(entry_name, parent_descriptor, None, unsafe_path_prefix)",
  "            assert_managed_parent_stable(path, parent_identity, unsafe_path_prefix)",
  "            return b'', None, None, parent_descriptor, parent_identity",
  "        except OSError as exc:",
  "            unsafe_path_kind = None",
  "            if unsafe_path_prefix:",
  "                if exc.errno == errno.ELOOP:",
  "                    unsafe_path_kind = 'symbolic link'",
  "                else:",
  "                    try:",
  "                        unsafe_path_kind = managed_projection_path_kind(os.stat(entry_name, dir_fd=parent_descriptor, follow_symlinks=False).st_mode)",
  "                    except OSError:",
  "                        pass",
  "            if unsafe_path_kind:",
  "                raise ValueError(f'{unsafe_path_prefix}: {unsafe_path_kind}') from exc",
  "            raise",
  "        try:",
  "            before = os.fstat(descriptor)",
  "            if unsafe_path_prefix:",
  "                unsafe_path_kind = managed_projection_path_kind(before.st_mode)",
  "                if unsafe_path_kind:",
  "                    raise ValueError(f'{unsafe_path_prefix}: {unsafe_path_kind}')",
  "            validate_managed_descriptor_path(entry_name, parent_descriptor, descriptor, unsafe_path_prefix)",
  "            if before.st_size < 0 or before.st_size > MANAGED_MCP_MAX_BYTES:",
  "                raise ValueError('managed MCP projection has invalid size')",
  "            chunks = []",
  "            remaining = before.st_size",
  "            while remaining:",
  "                chunk = os.read(descriptor, remaining)",
  "                if not chunk:",
  "                    break",
  "                chunks.append(chunk)",
  "                remaining -= len(chunk)",
  "            after = os.fstat(descriptor)",
  "            linked_after = os.stat(entry_name, dir_fd=parent_descriptor, follow_symlinks=False)",
  "            if unsafe_path_prefix:",
  "                unsafe_path_kind = managed_projection_path_kind(linked_after.st_mode)",
  "                if unsafe_path_kind:",
  "                    raise ValueError(f'{unsafe_path_prefix}: {unsafe_path_kind}')",
  "            stable = (managed_fingerprint(before) == managed_fingerprint(after) and managed_fingerprint(after) == managed_fingerprint(linked_after))",
  "            if remaining or not stable:",
  "                raise ValueError('managed MCP projection changed while reading')",
  "            assert_managed_parent_stable(path, parent_identity, unsafe_path_prefix)",
  "            return b''.join(chunks), managed_fingerprint(after), descriptor, parent_descriptor, parent_identity",
  "        except Exception:",
  "            os.close(descriptor)",
  "            raise",
  "    except Exception:",
  "        os.close(parent_descriptor)",
  "        raise",
  "def decode_managed_projection(raw):",
  "    return strict_json_loads(raw.decode('utf-8')) if raw else {}",
  "def close_managed_projection_descriptors(descriptor, parent_descriptor):",
  "    for current in (descriptor, parent_descriptor):",
  "        if current is None:",
  "            continue",
  "        try:",
  "            os.close(current)",
  "        except OSError:",
  "            pass",
  "def read_managed_projection(path, unsafe_path_prefix=None):",
  "    raw, identity, descriptor, parent_descriptor, _ = open_managed_projection(path, unsafe_path_prefix=unsafe_path_prefix)",
  "    try:",
  "        return decode_managed_projection(raw), identity",
  "    finally:",
  "        close_managed_projection_descriptors(descriptor, parent_descriptor)",
];

export const DEEPAGENTS_MANAGED_PROJECTION_MUTATION_HELPERS = [
  "def load_managed_projection_for_update(path):",
  "    raw, identity, descriptor, parent_descriptor, parent_identity = open_managed_projection(path, True)",
  "    try:",
  "        return decode_managed_projection(raw), identity, descriptor, parent_descriptor, parent_identity",
  "    except Exception:",
  "        close_managed_projection_descriptors(descriptor, parent_descriptor)",
  "        raise",
  "def managed_projection_bytes(value):",
  "    payload = (json.dumps(value, indent=2, sort_keys=True) + '\\n').encode('utf-8')",
  "    if not payload or len(payload) > MANAGED_MCP_MAX_BYTES:",
  "        raise ValueError('managed MCP projection has invalid rendered size')",
  "    return payload",
  "def rewrite_managed_projection(path, value, identity, descriptor, parent_descriptor, parent_identity):",
  "    if identity is None or descriptor is None or parent_descriptor is None or parent_identity is None:",
  "        raise ValueError('managed MCP projection descriptor is unavailable')",
  "    assert_managed_parent_stable(path, parent_identity)",
  "    assert_managed_source_stable(path.name, parent_descriptor, identity)",
  "    payload = managed_projection_bytes(value)",
  "    os.lseek(descriptor, 0, os.SEEK_SET)",
  "    os.ftruncate(descriptor, 0)",
  "    offset = 0",
  "    while offset < len(payload):",
  "        written = os.write(descriptor, payload[offset:])",
  "        if written <= 0:",
  "            raise OSError('managed MCP projection write made no progress')",
  "        offset += written",
  "    os.fsync(descriptor)",
  "    os.lseek(descriptor, 0, os.SEEK_SET)",
  "    persisted = os.read(descriptor, len(payload) + 1)",
  "    if persisted != payload or os.fstat(descriptor).st_size != len(payload):",
  "        raise ValueError('managed MCP projection verification failed')",
  "    validate_managed_descriptor_path(path.name, parent_descriptor, descriptor)",
  "    assert_managed_parent_stable(path, parent_identity)",
  "def create_managed_projection_temp(parent_descriptor):",
  "    flags = os.O_RDWR | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC | os.O_NOFOLLOW",
  "    for _ in range(16):",
  "        name = '.nemoclaw-mcp.' + os.urandom(16).hex()",
  "        try:",
  "            return os.open(name, flags, 0o600, dir_fd=parent_descriptor), name",
  "        except FileExistsError:",
  "            pass",
  "    raise FileExistsError('could not allocate managed MCP projection temporary file')",
  "def publish_absent_managed_projection(path, value, parent_descriptor, parent_identity):",
  "    owns_parent_descriptor = parent_descriptor is None",
  "    if parent_descriptor is None:",
  "        parent_descriptor, parent_identity, created = open_managed_parent(path, True)",
  "        if not created:",
  "            os.close(parent_descriptor)",
  "            raise ValueError('managed MCP projection parent appeared during publication')",
  "    try:",
  "        if not owns_parent_descriptor:",
  "            assert_managed_parent_stable(path, parent_identity)",
  "        assert_managed_source_stable(path.name, parent_descriptor, None)",
  "        payload = managed_projection_bytes(value)",
  "        tmp_fd, tmp_name = create_managed_projection_temp(parent_descriptor)",
  "        try:",
  "            with os.fdopen(tmp_fd, 'wb') as tmp_file:",
  "                tmp_file.write(payload)",
  "                tmp_file.flush()",
  "                os.fsync(tmp_file.fileno())",
  "            try:",
  "                os.link(tmp_name, path.name, src_dir_fd=parent_descriptor, dst_dir_fd=parent_descriptor, follow_symlinks=False)",
  "            except FileExistsError as exc:",
  "                raise ValueError('managed MCP projection appeared during publication') from exc",
  "            os.unlink(tmp_name, dir_fd=parent_descriptor)",
  "        finally:",
  "            try:",
  "                os.unlink(tmp_name, dir_fd=parent_descriptor)",
  "            except FileNotFoundError:",
  "                pass",
  "        assert_managed_parent_stable(path, parent_identity)",
  "        persisted, _ = read_managed_projection(path)",
  "        if persisted != value:",
  "            raise ValueError('managed MCP projection verification failed')",
  "    finally:",
  "        if owns_parent_descriptor:",
  "            os.close(parent_descriptor)",
  "def write_managed_projection(path, value, identity, descriptor, parent_descriptor, parent_identity):",
  "    try:",
  "        if identity is None:",
  "            if descriptor is not None:",
  "                raise ValueError('unexpected managed MCP projection descriptor')",
  "            publish_absent_managed_projection(path, value, parent_descriptor, parent_identity)",
  "        else:",
  "            rewrite_managed_projection(path, value, identity, descriptor, parent_descriptor, parent_identity)",
  "    finally:",
  "        close_managed_projection_descriptors(descriptor, parent_descriptor)",
];

export const DEEPAGENTS_MANAGED_PROJECTION_HELPERS = [
  ...DEEPAGENTS_MANAGED_PROJECTION_READ_HELPERS,
  ...DEEPAGENTS_MANAGED_PROJECTION_MUTATION_HELPERS,
];
