// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { McpBridgeEntry } from "../../state/registry";
import { runDeepAgentsAdapterCommand } from "./mcp-bridge-adapter-deepagents-command";
import {
  DEEPAGENTS_LEGACY_CONFIG_HELPERS,
  DEEPAGENTS_LEGACY_MCP_CONFIG_PATH,
} from "./mcp-bridge/deepagents-legacy-config";
import {
  DEEPAGENTS_MANAGED_PROJECTION_HELPERS,
  DEEPAGENTS_STRICT_JSON_HELPERS,
} from "./mcp-bridge-adapter-deepagents-projection";
import type {
  AdapterMutationOptions,
  AdapterRemovalOutcome,
} from "./mcp-bridge-adapter-inspection";
import {
  MANAGED_HTTP_SERVER_MATCH_HELPERS,
  DEEPAGENTS_MCP_CONFIG_PATH,
  deepAgentsManagedServerConfig,
  pythonJsonLiteral,
} from "./mcp-bridge-adapter-status";

export function buildDeepAgentsMcpRemoveCommand(
  entry: McpBridgeEntry,
  force = false,
  adaptiveTeardown = false,
): string {
  const payload = {
    server: entry.server,
    expected: deepAgentsManagedServerConfig(entry),
    force,
  };
  return [
    "/opt/venv/bin/python3 -I - <<'PY'",
    "import json, os, pathlib, stat, sys",
    `payload = json.loads(${pythonJsonLiteral(payload)})`,
    `managed_path = pathlib.Path(${JSON.stringify(DEEPAGENTS_MCP_CONFIG_PATH)})`,
    `legacy_path = pathlib.Path(${JSON.stringify(DEEPAGENTS_LEGACY_MCP_CONFIG_PATH)})`,
    ...DEEPAGENTS_STRICT_JSON_HELPERS,
    ...DEEPAGENTS_MANAGED_PROJECTION_HELPERS,
    ...DEEPAGENTS_LEGACY_CONFIG_HELPERS,
    ...MANAGED_HTTP_SERVER_MATCH_HELPERS,
    `runtime_kind = "${adaptiveTeardown ? "auto" : "v2"}"`,
    "if runtime_kind == 'auto':",
    "    runtime_kind = 'unknown'",
    "    try:",
    "        from deepagents_code import _nemoclaw_managed as managed",
    "        runtime_path = str(getattr(managed, '_MCP_CONFIG_FILE', ''))",
    "        if runtime_path == str(managed_path):",
    "            runtime_kind = 'v2'",
    "        elif runtime_path == str(legacy_path):",
    "            runtime_kind = 'legacy'",
    "    except Exception:",
    "        pass",
    "if runtime_kind not in ('v2', 'legacy'):",
    "    print('Could not identify the managed Deep Agents MCP runtime; refusing teardown', file=sys.stderr)",
    "    raise SystemExit(2)",
    "is_v2 = runtime_kind == 'v2'",
    "config_path = managed_path if is_v2 else legacy_path",
    "managed_identity = None",
    "managed_descriptor = None",
    "managed_parent_identity = None",
    "managed_parent_descriptor = None",
    "legacy_identity = None",
    "legacy_descriptor = None",
    "legacy_parent_identity = None",
    "legacy_parent_descriptor = None",
    "def finish(outcome):",
    "    close_managed_projection_descriptors(managed_descriptor, managed_parent_descriptor)",
    "    close_legacy_config_descriptors(legacy_descriptor, legacy_parent_descriptor)",
    "    print('NEMOCLAW_DEEPAGENTS_MCP_REMOVAL=' + outcome)",
    "    raise SystemExit(0)",
    "def fail_teardown(message):",
    "    close_managed_projection_descriptors(managed_descriptor, managed_parent_descriptor)",
    "    close_legacy_config_descriptors(legacy_descriptor, legacy_parent_descriptor)",
    "    print(message, file=sys.stderr)",
    "    raise SystemExit(2)",
    "def repair_v2_projection(identity, descriptor, parent_descriptor, parent_identity):",
    "    try:",
    "        write_managed_projection(config_path, {'mcpServers': {}}, identity, descriptor, parent_descriptor, parent_identity)",
    "    except (OSError, ValueError) as exc:",
    "        fail_teardown(f'Refusing unsafe managed MCP v2 repair at {config_path}: {exc}')",
    "if is_v2:",
    "    try:",
    "        raw, managed_identity, managed_descriptor, managed_parent_descriptor, managed_parent_identity = open_managed_projection(config_path, True)",
    "    except (OSError, ValueError) as exc:",
    "        fail_teardown(f'Invalid managed MCP v2 projection at {config_path}: {exc}')",
    "    if managed_descriptor is None:",
    "        finish('absent')",
    "    try:",
    "        data = decode_managed_projection(raw)",
    "    except (UnicodeDecodeError, ValueError) as exc:",
    "        if payload['force']:",
    "            repair_v2_projection(managed_identity, managed_descriptor, managed_parent_descriptor, managed_parent_identity)",
    "            finish('removed')",
    "        fail_teardown(f'Invalid managed MCP v2 projection at {config_path}: {exc}')",
    "else:",
    "    try:",
    "        data, legacy_identity, legacy_descriptor, legacy_parent_descriptor, legacy_parent_identity = load_legacy_config_for_update(config_path)",
    "    except (OSError, UnicodeDecodeError, ValueError) as exc:",
    "        if str(exc).startswith('legacy MCP config parent is unsafe'):",
    "            fail_teardown(f'Refusing unsafe legacy MCP teardown at {config_path}: {exc}')",
    "        finish('unowned')",
    "    if legacy_descriptor is None:",
    "        finish('absent')",
    "if not isinstance(data, dict):",
    "    if is_v2 and payload['force']:",
    "        repair_v2_projection(managed_identity, managed_descriptor, managed_parent_descriptor, managed_parent_identity)",
    "        finish('removed')",
    "    if is_v2:",
    "        fail_teardown(f'Invalid managed MCP v2 projection at {config_path}: expected object')",
    "    finish('unowned')",
    "servers = data.get('mcpServers')",
    "if not isinstance(servers, dict):",
    "    if not is_v2 and 'mcpServers' not in data:",
    "        finish('absent')",
    "    if is_v2 and payload['force']:",
    "        repair_v2_projection(managed_identity, managed_descriptor, managed_parent_descriptor, managed_parent_identity)",
    "        finish('removed')",
    "    if is_v2:",
    "        fail_teardown(f'Invalid managed MCP v2 server map at {config_path}')",
    "    finish('unowned')",
    "present = payload['server'] in servers",
    "current = servers.get(payload['server'])",
    "if is_v2:",
    "    if data and set(data) != {'mcpServers'}:",
    "        if payload['force']:",
    "            repair_v2_projection(managed_identity, managed_descriptor, managed_parent_descriptor, managed_parent_identity)",
    "            finish('removed')",
    "        fail_teardown(f'Invalid managed MCP v2 projection at {config_path}: only mcpServers is allowed')",
    "    if present and not payload['force'] and not managed_http_server_matches(current, payload['expected'], True):",
    "        fail_teardown(f\"Refusing to remove modified MCP server '{payload['server']}' from {config_path}. Use --force to remove it.\")",
    "    if not present:",
    "        finish('absent')",
    "else:",
    "    if not present:",
    "        finish('absent')",
    "    if not managed_http_server_matches(current, payload['expected'], True) and not payload['force']:",
    "        finish('unowned')",
    "servers.pop(payload['server'])",
    "if is_v2:",
    "    data = {'mcpServers': servers}",
    "elif not servers:",
    "    data.pop('mcpServers', None)",
    "if data:",
    "    try:",
    "        if is_v2:",
    "            write_managed_projection(config_path, data, managed_identity, managed_descriptor, managed_parent_descriptor, managed_parent_identity)",
    "            persisted = read_managed_projection(config_path)[0]",
    "        else:",
    "            persisted = write_legacy_config(config_path, data, legacy_identity, legacy_descriptor, legacy_parent_descriptor, legacy_parent_identity)",
    "    except (OSError, UnicodeDecodeError, ValueError) as exc:",
    "        fail_teardown(f'MCP teardown mutation failed at {config_path}: {exc}')",
    "    if persisted != data:",
    "        fail_teardown(f'MCP teardown verification failed at {config_path}')",
    "else:",
    "    try:",
    "        remove_legacy_config(config_path, legacy_identity, legacy_descriptor, legacy_parent_descriptor, legacy_parent_identity)",
    "    except (OSError, ValueError) as exc:",
    "        fail_teardown(f'MCP teardown mutation failed at {config_path}: {exc}')",
    "finish('removed')",
    "PY",
  ].join("\n");
}

export function unregisterDeepAgentsAdapter(
  sandboxName: string,
  entry: McpBridgeEntry,
  options: AdapterMutationOptions = {},
): AdapterRemovalOutcome {
  const stdout = runDeepAgentsAdapterCommand(
    sandboxName,
    entry,
    buildDeepAgentsMcpRemoveCommand(entry, options.force === true, options.teardown === true),
    `Deep Agents Code MCP config removal failed for '${entry.server}'.`,
    options,
  );
  const marker = stdout.match(/NEMOCLAW_DEEPAGENTS_MCP_REMOVAL=(removed|absent|unowned)/);
  return (marker?.[1] as AdapterRemovalOutcome | undefined) ?? "unowned";
}
