// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { describe, expect, it, vi } from "vitest";

import { detectSandboxFallbackDns, parseResolvConfNameservers } from "./docker-gpu-dns-fallback";

describe("parseResolvConfNameservers", () => {
  it("parses loopback and direct nameservers across resolv.conf whitespace", () => {
    expect(
      parseResolvConfNameservers(
        "# generated\n  nameserver 127.0.0.53\n\tnameserver\t192.168.1.1\nsearch lan\n",
      ),
    ).toEqual(["127.0.0.53", "192.168.1.1"]);
  });

  it("ignores empty and malformed resolver lines", () => {
    expect(
      parseResolvConfNameservers("\nsearch lan\nnameserver\nnot-a-resolver 8.8.8.8\n"),
    ).toEqual([]);
  });
});

describe("detectSandboxFallbackDns", () => {
  it("returns the systemd-resolved upstream when /etc/resolv.conf is loopback-only", () => {
    const files: Record<string, string> = {
      "/etc/resolv.conf": "nameserver 127.0.0.53\nsearch lan\n",
      "/run/systemd/resolve/resolv.conf":
        "# Generated by systemd-resolved\nnameserver 8.8.8.8\nnameserver 1.1.1.1\n",
    };

    expect(detectSandboxFallbackDns({ readFile: (path) => files[path] ?? null })).toBe("8.8.8.8");
  });

  it("returns null without a loopback-only resolver and usable systemd upstream", () => {
    expect(detectSandboxFallbackDns({ readFile: () => "nameserver 192.168.1.1\n" })).toBeNull();
    expect(detectSandboxFallbackDns({ readFile: () => null })).toBeNull();
    expect(
      detectSandboxFallbackDns({
        readFile: (path) => (path === "/etc/resolv.conf" ? "nameserver 127.0.0.53\n" : null),
      }),
    ).toBeNull();
  });

  it("does not read the upstream file for a direct or mixed resolver configuration", () => {
    const directRead = vi.fn(() => "nameserver 192.168.1.1\n");
    expect(detectSandboxFallbackDns({ readFile: directRead })).toBeNull();
    expect(directRead).toHaveBeenCalledTimes(1);

    const files: Record<string, string> = {
      "/etc/resolv.conf": "nameserver 127.0.0.53\nnameserver 10.0.0.2\n",
      "/run/systemd/resolve/resolv.conf": "nameserver 8.8.8.8\n",
    };
    const mixedRead = vi.fn((path: string) => files[path] ?? null);
    expect(detectSandboxFallbackDns({ readFile: mixedRead })).toBeNull();
    expect(mixedRead).toHaveBeenCalledTimes(1);
  });

  it("returns null for empty, missing, unreadable, or malformed resolver files", () => {
    expect(detectSandboxFallbackDns({ readFile: () => "" })).toBeNull();
    expect(detectSandboxFallbackDns({ readFile: () => null })).toBeNull();
    expect(detectSandboxFallbackDns({ readFile: () => "search lan\nnameserver\n" })).toBeNull();

    const unreadableUpstream = vi
      .fn()
      .mockReturnValueOnce("nameserver 127.0.0.53\n")
      .mockReturnValueOnce(null);
    expect(detectSandboxFallbackDns({ readFile: unreadableUpstream })).toBeNull();
    expect(unreadableUpstream).toHaveBeenCalledTimes(2);
  });

  it("ignores loopback-only or malformed upstream entries", () => {
    const loopbackOnly = vi
      .fn()
      .mockReturnValueOnce("nameserver 127.0.0.53\n")
      .mockReturnValueOnce("nameserver 127.0.0.54\n");
    expect(detectSandboxFallbackDns({ readFile: loopbackOnly })).toBeNull();

    const malformed = vi
      .fn()
      .mockReturnValueOnce("nameserver 127.0.0.53\n")
      .mockReturnValueOnce("search lan\nnameserver\n");
    expect(detectSandboxFallbackDns({ readFile: malformed })).toBeNull();
  });
});
