// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::{collections::BTreeMap, fs, io, path::Path};

/// Durable identities only; suitable for comparison and evidence without dumping attributes.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize)]
#[serde(transparent)]
pub struct ResourceIdentities(BTreeMap<String, String>);

impl ResourceIdentities {
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Check replacement of one binding while independent bindings remain unchanged.
    pub fn require_replacement(&self, after: &Self, address: &str) -> Result<(), String> {
        if !self.0.contains_key(address) || !self.0.keys().eq(after.0.keys()) {
            return Err("replacement must preserve the complete resource address set".into());
        }
        for (key, id) in &self.0 {
            let valid = if key == address {
                after.0.get(key).is_some_and(|next| next != id)
            } else {
                after.0.get(key) == Some(id)
            };
            if !valid {
                return Err(format!("unexpected identity transition: {key}"));
            }
        }
        Ok(())
    }

    pub fn merge(&mut self, other: Self) -> Result<(), String> {
        if self.0.keys().any(|key| other.0.contains_key(key)) {
            return Err("duplicate resource address across state files".into());
        }
        self.0.extend(other.0);
        Ok(())
    }
}

/// The single-instance root resources generated by the deployment SDK.
/// Reject unsupported layouts rather than compare an incomplete observation.
#[derive(Default)]
pub struct StateSnapshot {
    resources: BTreeMap<String, Resource>,
}

// State attributes can contain credentials. Do not include them in panic diagnostics.
impl std::fmt::Debug for StateSnapshot {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("StateSnapshot")
            .field("resource_count", &self.resources.len())
            .finish()
    }
}

struct Resource {
    kind: String,
    id: String,
    attributes: Value,
}

#[derive(Deserialize)]
struct State {
    resources: Vec<StateResource>,
}

#[derive(Deserialize)]
struct StateResource {
    #[serde(rename = "type")]
    kind: String,
    name: String,
    module: Option<String>,
    mode: Option<String>,
    instances: Vec<Instance>,
}

#[derive(Deserialize)]
struct Instance {
    index_key: Option<Value>,
    deposed: Option<Value>,
    attributes: Value,
}

impl StateSnapshot {
    pub fn parse(bytes: &[u8]) -> io::Result<Self> {
        let state: State = serde_json::from_slice(bytes)
            .map_err(|_| invalid("invalid deployment state structure"))?;
        let mut resources = BTreeMap::new();
        for resource in state.resources {
            if resource.kind.is_empty()
                || resource.name.is_empty()
                || resource.module.is_some()
                || resource
                    .mode
                    .as_deref()
                    .is_some_and(|mode| mode != "managed")
                || resource.instances.len() != 1
            {
                return Err(invalid("expected single-instance managed root resource"));
            }
            let instance = resource
                .instances
                .into_iter()
                .next()
                .expect("checked length");
            if instance.index_key.is_some() || instance.deposed.is_some() {
                return Err(invalid("indexed or deposed resource is not supported"));
            }
            let id = instance.attributes["id"]
                .as_str()
                .filter(|id| !id.is_empty())
                .ok_or_else(|| invalid("resource identity must be a nonempty string"))?
                .to_owned();
            let address = format!("{}.{}", resource.kind, resource.name);
            if resources
                .insert(
                    address,
                    Resource {
                        kind: resource.kind,
                        id,
                        attributes: instance.attributes,
                    },
                )
                .is_some()
            {
                return Err(invalid("duplicate resource address"));
            }
        }
        Ok(Self { resources })
    }

    pub fn read(path: &Path) -> io::Result<Self> {
        Self::parse(&fs::read(path)?)
            .map_err(|error| io::Error::new(error.kind(), format!("{}: {error}", path.display())))
    }

    /// External-gateway deployments need not have managed runtime state.
    /// Only confirmed absence is empty; malformed or unreadable state is an error.
    pub fn read_optional(path: &Path) -> io::Result<Self> {
        match fs::read(path) {
            Ok(bytes) => Self::parse(&bytes),
            Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(Self::default()),
            Err(error) => Err(error),
        }
    }

    pub fn len(&self) -> usize {
        self.resources.len()
    }
    pub fn is_empty(&self) -> bool {
        self.resources.is_empty()
    }

    pub fn identities(&self) -> ResourceIdentities {
        ResourceIdentities(
            self.resources
                .iter()
                .map(|(key, resource)| (key.clone(), resource.id.clone()))
                .collect(),
        )
    }

    /// Full bindings for in-memory drift checks. Do not publish as sanitized evidence.
    pub fn attributes(&self) -> BTreeMap<String, Value> {
        self.resources
            .iter()
            .map(|(key, resource)| (key.clone(), resource.attributes.clone()))
            .collect()
    }

    pub fn only(&self, kind: &str) -> io::Result<&Value> {
        let mut matching = self
            .resources
            .values()
            .filter(|resource| resource.kind == kind);
        let first = matching
            .next()
            .ok_or_else(|| invalid("required resource binding is missing"))?;
        if matching.next().is_some() {
            return Err(invalid(
                "expected exactly one resource of the requested type",
            ));
        }
        Ok(&first.attributes)
    }
}

fn invalid(message: &str) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, message)
}
