// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#[cfg(test)]
mod scenarios;
mod tui;

use clap::Parser;
use nemoclaw_authoring::{Answers, Capabilities, Draft, Session};
use nemoclaw_sdk::{CancellationToken, config::MAX_DOCUMENT_BYTES};
use std::{
    io::{IsTerminal, Read, Write},
    path::{Path, PathBuf},
    process::ExitCode,
};

#[derive(Debug, Parser)]
#[command(
    name = "nemoclaw-onboarding",
    version,
    about = "Run an example NemoClaw authoring experience",
    long_about = "Run an example terminal frontend over nemoclaw-authoring. This command generates desired-state YAML only; it does not resolve credentials, plan, or apply a deployment."
)]
struct Cli {
    /// Write the authored YAML to this path.
    #[arg(short, long, value_name = "FILE", default_value = "deployment.yaml")]
    output: PathBuf,
    /// Open a document generated by this example for guided editing.
    #[arg(long, value_name = "FILE")]
    edit: Option<PathBuf>,
}

#[tokio::main]
async fn main() -> ExitCode {
    let cli = Cli::parse();
    if !std::io::stdin().is_terminal() {
        eprintln!("the example onboarding TUI requires a terminal on stdin");
        return ExitCode::FAILURE;
    }

    let cancel = CancellationToken::new();
    let signal = cancel.clone();
    let interruption = match interrupt() {
        Ok(interruption) => interruption,
        Err(error) => {
            eprintln!("cannot listen for interruption: {error}");
            return ExitCode::FAILURE;
        }
    };
    let signals = tokio::spawn(async move {
        interruption.await;
        signal.cancel();
    });
    let result = author(cli, &cancel);
    signals.abort();
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{error}");
            ExitCode::FAILURE
        }
    }
}

fn author(cli: Cli, cancel: &CancellationToken) -> Result<(), Box<dyn std::error::Error>> {
    let capabilities = Capabilities::available();
    let draft = match cli.edit {
        Some(path) => read_draft(&path)?,
        None => {
            let authored =
                Session::new()?.project(&capabilities, &Answers::onboarding_defaults())?;
            Draft::from_document(authored.document().clone())?
        }
    };
    draft.guided_answers(&capabilities)?;
    let Some(draft) = tui::run(capabilities, draft, cancel)? else {
        return Ok(());
    };
    let review = draft.review()?;
    write_path(&cli.output, review.yaml().as_bytes())?;
    eprintln!("Authored desired state: {}", cli.output.display());
    eprintln!(
        "Credential references: {}",
        review.credential_references().join(", ")
    );
    Ok(())
}

fn read_draft(path: &Path) -> Result<Draft, Box<dyn std::error::Error>> {
    let mut bytes = Vec::new();
    std::fs::File::open(path)?
        .take(MAX_DOCUMENT_BYTES + 1)
        .read_to_end(&mut bytes)?;
    if bytes.len() as u64 > MAX_DOCUMENT_BYTES {
        return Err("configuration exceeds 1 MiB".into());
    }
    Ok(Draft::from_yaml(&bytes)?)
}

fn write_path(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or(Path::new("."));
    let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
    temporary.write_all(bytes)?;
    temporary.as_file().sync_all()?;
    temporary.persist(path).map_err(|error| error.error)?;
    Ok(())
}

fn interrupt() -> std::io::Result<impl std::future::Future<Output = ()>> {
    #[cfg(unix)]
    {
        use tokio::signal::unix::{SignalKind, signal};
        let mut interruption = signal(SignalKind::interrupt())?;
        let mut termination = signal(SignalKind::terminate())?;
        Ok(async move {
            tokio::select! { _ = interruption.recv() => {}, _ = termination.recv() => {} }
        })
    }
    #[cfg(not(unix))]
    {
        Ok(async {
            let _ = tokio::signal::ctrl_c().await;
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::{CommandFactory, error::ErrorKind};

    #[test]
    fn example_command_exposes_only_generation_inputs() {
        Cli::command().debug_assert();
        let cli = Cli::try_parse_from([
            "nemoclaw-onboarding",
            "--output",
            "draft.yaml",
            "--edit",
            "existing.yaml",
        ])
        .unwrap();
        assert_eq!(cli.output, PathBuf::from("draft.yaml"));
        assert_eq!(cli.edit, Some(PathBuf::from("existing.yaml")));
        for unsupported in ["--apply", "--state-dir", "--bundle", "--non-interactive"] {
            assert_eq!(
                Cli::try_parse_from(["nemoclaw-onboarding", unsupported])
                    .err()
                    .unwrap()
                    .kind(),
                ErrorKind::UnknownArgument
            );
        }
    }

    #[test]
    fn generated_output_is_atomically_parseable() {
        let directory = tempfile::tempdir().unwrap();
        let output = directory.path().join("deployment.yaml");
        let capabilities = Capabilities::available();
        let authored = Session::new()
            .unwrap()
            .project(&capabilities, &Answers::onboarding_defaults())
            .unwrap();
        write_path(&output, authored.yaml().as_bytes()).unwrap();
        let document =
            nemoclaw_sdk::config::Document::parse(std::fs::File::open(&output).unwrap()).unwrap();
        assert_eq!(&document, authored.document());
    }

    #[test]
    fn oversized_edit_input_is_rejected() {
        let directory = tempfile::tempdir().unwrap();
        let input = directory.path().join("large.yaml");
        std::fs::write(&input, vec![b' '; (MAX_DOCUMENT_BYTES + 1) as usize]).unwrap();
        assert_eq!(
            read_draft(&input).unwrap_err().to_string(),
            "configuration exceeds 1 MiB"
        );
    }
}
