[package]
name = "nemoclaw-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
nemoclaw-sdk = { path = "../nemoclaw-sdk" }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tf-provider.workspace = true
tokio.workspace = true

[lints]
workspace = true
