// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

const MINUTE_MS = 60_000;

export const SANDBOX_SURVIVAL_REPAIR_COMMANDS = ["recover", "start"] as const;
export const SANDBOX_SURVIVAL_MARKER_PATHS = [
  "/sandbox/.openclaw/workspace/.survival-workspace-marker",
  "/sandbox/.openclaw/agents/main/sessions/.survival-session-marker",
  "/sandbox/.openclaw/memory/.survival-memory-marker",
] as const;

export const SANDBOX_SURVIVAL_NATIVE_READINESS = {
  attempts: 10,
  delayMs: 5_000,
  timeoutMs: 15_000,
} as const;
export const SANDBOX_SURVIVAL_HOST_FORWARD_READINESS = {
  attempts: 10,
  delayMs: 5_000,
  timeoutMs: 10_000,
} as const;
export const SANDBOX_SURVIVAL_LIFECYCLE_READINESS = {
  attempts: 10,
  delayMs: 5_000,
  timeoutMs: 15_000,
} as const;

export const SANDBOX_SURVIVAL_INSTALL_TIMEOUT_MS = 20 * MINUTE_MS;
export const SANDBOX_SURVIVAL_PRE_CLEANUP_TIMEOUT_MS = 2 * MINUTE_MS;
export const SANDBOX_SURVIVAL_OPENSHELL_DELETE_TIMEOUT_MS = 2 * MINUTE_MS;
export const SANDBOX_SURVIVAL_GATEWAY_STOP_BUDGET_MS = 5 * MINUTE_MS;
export const SANDBOX_SURVIVAL_GATEWAY_DESTROY_TIMEOUT_MS = 2 * MINUTE_MS;
export const SANDBOX_SURVIVAL_PREREQUISITE_TIMEOUT_MS = 30_000;
export const SANDBOX_SURVIVAL_REPAIR_TIMEOUT_MS = 3 * MINUTE_MS;
export const SANDBOX_SURVIVAL_FINAL_DESTROY_TIMEOUT_MS = 15 * MINUTE_MS;
export const SANDBOX_SURVIVAL_POST_DESTROY_LIST_TIMEOUT_MS = MINUTE_MS;

export const SANDBOX_SURVIVAL_RECOVERY_OPERATION_TIMEOUTS = {
  directStartMs: MINUTE_MS,
  inspectMs: 30_000,
  phaseReadMs: 30_000,
  resourceLookupMs: 30_000,
  stopMs: 2 * MINUTE_MS,
} as const;

const repairCount = SANDBOX_SURVIVAL_REPAIR_COMMANDS.length;
export const SANDBOX_SURVIVAL_NATIVE_READINESS_POLLS = 1 + repairCount;
export const SANDBOX_SURVIVAL_HOST_FORWARD_POLLS = repairCount;
export const SANDBOX_SURVIVAL_LIFECYCLE_READINESS_POLLS = repairCount;
export const SANDBOX_SURVIVAL_BASELINE_EXEC_PROBES = 1;

export const SANDBOX_SURVIVAL_READINESS_WORST_CASE_MS =
  SANDBOX_SURVIVAL_BASELINE_EXEC_PROBES * SANDBOX_SURVIVAL_NATIVE_READINESS.timeoutMs +
  SANDBOX_SURVIVAL_NATIVE_READINESS_POLLS *
    SANDBOX_SURVIVAL_NATIVE_READINESS.attempts *
    (SANDBOX_SURVIVAL_NATIVE_READINESS.timeoutMs + SANDBOX_SURVIVAL_NATIVE_READINESS.delayMs) +
  SANDBOX_SURVIVAL_HOST_FORWARD_POLLS *
    SANDBOX_SURVIVAL_HOST_FORWARD_READINESS.attempts *
    (SANDBOX_SURVIVAL_HOST_FORWARD_READINESS.timeoutMs +
      SANDBOX_SURVIVAL_HOST_FORWARD_READINESS.delayMs) +
  SANDBOX_SURVIVAL_LIFECYCLE_READINESS_POLLS *
    SANDBOX_SURVIVAL_LIFECYCLE_READINESS.attempts *
    (SANDBOX_SURVIVAL_LIFECYCLE_READINESS.timeoutMs + SANDBOX_SURVIVAL_LIFECYCLE_READINESS.delayMs);

export const SANDBOX_SURVIVAL_PREPARATION_WORST_CASE_MS =
  SANDBOX_SURVIVAL_PREREQUISITE_TIMEOUT_MS +
  SANDBOX_SURVIVAL_PRE_CLEANUP_TIMEOUT_MS +
  SANDBOX_SURVIVAL_OPENSHELL_DELETE_TIMEOUT_MS +
  SANDBOX_SURVIVAL_GATEWAY_STOP_BUDGET_MS +
  SANDBOX_SURVIVAL_GATEWAY_DESTROY_TIMEOUT_MS +
  SANDBOX_SURVIVAL_INSTALL_TIMEOUT_MS;

export const SANDBOX_SURVIVAL_RECOVERY_MUTATION_WORST_CASE_MS =
  SANDBOX_SURVIVAL_RECOVERY_OPERATION_TIMEOUTS.resourceLookupMs +
  repairCount *
    (SANDBOX_SURVIVAL_RECOVERY_OPERATION_TIMEOUTS.stopMs +
      SANDBOX_SURVIVAL_RECOVERY_OPERATION_TIMEOUTS.directStartMs +
      SANDBOX_SURVIVAL_RECOVERY_OPERATION_TIMEOUTS.phaseReadMs +
      SANDBOX_SURVIVAL_RECOVERY_OPERATION_TIMEOUTS.inspectMs +
      SANDBOX_SURVIVAL_REPAIR_TIMEOUT_MS +
      SANDBOX_SURVIVAL_RECOVERY_OPERATION_TIMEOUTS.resourceLookupMs);

// The rounded phase budgets contain the configured operation ceilings plus
// smaller setup, state-validation, and diagnostic commands in each phase.
export const SANDBOX_SURVIVAL_PREPARATION_BUDGET_MS = 35 * MINUTE_MS;
export const SANDBOX_SURVIVAL_READINESS_BUDGET_MS = 25 * MINUTE_MS;
export const SANDBOX_SURVIVAL_RECOVERY_MUTATION_BUDGET_MS = 20 * MINUTE_MS;
export const SANDBOX_SURVIVAL_FINAL_VALIDATION_BUDGET_MS = 25 * MINUTE_MS;
export const SANDBOX_SURVIVAL_TEST_HEADROOM_MS = 5 * MINUTE_MS;

export const SANDBOX_SURVIVAL_TEST_TIMEOUT_MS =
  SANDBOX_SURVIVAL_PREPARATION_BUDGET_MS +
  SANDBOX_SURVIVAL_READINESS_BUDGET_MS +
  SANDBOX_SURVIVAL_RECOVERY_MUTATION_BUDGET_MS +
  SANDBOX_SURVIVAL_FINAL_VALIDATION_BUDGET_MS +
  SANDBOX_SURVIVAL_TEST_HEADROOM_MS;

export const SANDBOX_SURVIVAL_POST_TEST_CLEANUP_BUDGET_MS = 10 * MINUTE_MS;
export const SANDBOX_SURVIVAL_WORKFLOW_FINALIZATION_BUDGET_MS = 10 * MINUTE_MS;
export const SANDBOX_SURVIVAL_TARGET_TIMEOUT_MINUTES =
  (SANDBOX_SURVIVAL_TEST_TIMEOUT_MS +
    SANDBOX_SURVIVAL_POST_TEST_CLEANUP_BUDGET_MS +
    SANDBOX_SURVIVAL_WORKFLOW_FINALIZATION_BUDGET_MS) /
  MINUTE_MS;
