[package]
name = "nemoclaw-sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-saphyr.workspace = true
sha2.workspace = true
sha1.workspace = true
regex.workspace = true
url.workspace = true
ipnet.workspace = true
openshell-core.workspace = true
tonic.workspace = true
tokio.workspace = true
tempfile.workspace = true
getrandom.workspace = true
process-wrap.workspace = true
tokio-util.workspace = true
reqwest.workspace = true
futures-util.workspace = true
bollard.workspace = true
tar.workspace = true
time.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rustix.workspace = true
