# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# yaml-language-server: $schema=../schemas/nemoclaw-v1alpha1.schema.json

apiVersion: nemoclaw.nvidia.com/v1alpha1
kind: NemoClawConfig
metadata:
  name: local-agent
  uid: 87d485ad-fba7-4197-9eaa-aa97cc97446b
spec:
  gateway:
    management: external
    endpoint: http://127.0.0.1:17671
  inferenceProviders:
    - name: local
      provider: openai
      endpoint: http://172.20.0.1:11436/v1
      ollama:
        engine: unix:///var/run/docker.sock
        image: ollama/ollama@sha256:684d8674b4315fa18f4f0e973a118ec2652ed96f67563277839985175858e0ba
        network: nc-prototype-slice
  sandboxes:
    - name: assistant
      image:
        ref: nc-native-inference-b3e4ad457@sha256:427d7f46ff377e9d6fe28c28a534441c673226cb1b336c9d1efe740f7a7937a6
      runtime:
        provider: docker
      network:
        tier: isolated
      agents:
        - name: main
          harness:
            kind: openclaw
          inference:
            routes:
              - name: primary
                providerRef: local
                overrides:
                  model: qwen3:0.6b
