[package]
name = "nemoclaw-tofu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
nemoclaw-backend = { path = "../nemoclaw-backend" }
async-trait.workspace = true
tf-provider.workspace = true
