// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const DEEPAGENTS_LEGACY_MCP_CONFIG_PATH = "/sandbox/.deepagents/.mcp.json";

export const DEEPAGENTS_RUNTIME_SELECTION_HELPERS = [
  "def select_deepagents_runtime_kind(requested_kind, managed_path, legacy_path):",
  "    if requested_kind != 'auto':",
  "        return requested_kind",
  "    try:",
  "        from deepagents_code import _nemoclaw_managed as managed",
  "        runtime_path = str(getattr(managed, '_MCP_CONFIG_FILE', ''))",
  "        if runtime_path == str(managed_path):",
  "            return 'v2'",
  "        if runtime_path == str(legacy_path):",
  "            return 'legacy'",
  "    except Exception:",
  "        pass",
  "    return 'unknown'",
];

export const DEEPAGENTS_LEGACY_CONFIG_HELPERS = [
  "LEGACY_MCP_MAX_BYTES = 262144",
  "def legacy_fingerprint(metadata):",
  "    return (metadata.st_dev, metadata.st_ino, metadata.st_size, metadata.st_mtime_ns, metadata.st_ctime_ns, metadata.st_mode, metadata.st_nlink, metadata.st_uid)",
  "def validate_legacy_descriptor_path(entry_name, parent_descriptor, descriptor):",
  "    opened = os.fstat(descriptor)",
  "    linked = os.stat(entry_name, dir_fd=parent_descriptor, follow_symlinks=False)",
  "    safe = (stat.S_ISREG(opened.st_mode) and opened.st_uid == os.getuid() and stat.S_IMODE(opened.st_mode) == 0o600 and opened.st_nlink == 1 and (opened.st_dev, opened.st_ino) == (linked.st_dev, linked.st_ino))",
  "    if not safe:",
  "        raise ValueError('legacy MCP config has unsafe ownership, mode, type, or links')",
  "    return legacy_fingerprint(opened)",
  "def read_legacy_descriptor(entry_name, parent_descriptor, descriptor):",
  "    before = os.fstat(descriptor)",
  "    validate_legacy_descriptor_path(entry_name, parent_descriptor, descriptor)",
  "    if before.st_size <= 0 or before.st_size > LEGACY_MCP_MAX_BYTES:",
  "        raise ValueError('legacy MCP config has invalid size')",
  "    chunks = []",
  "    remaining = before.st_size",
  "    while remaining:",
  "        chunk = os.read(descriptor, remaining)",
  "        if not chunk:",
  "            break",
  "        chunks.append(chunk)",
  "        remaining -= len(chunk)",
  "    after = os.fstat(descriptor)",
  "    linked_after = os.stat(entry_name, dir_fd=parent_descriptor, follow_symlinks=False)",
  "    stable = (legacy_fingerprint(before) == legacy_fingerprint(after) and legacy_fingerprint(after) == legacy_fingerprint(linked_after))",
  "    if remaining or not stable:",
  "        raise ValueError('legacy MCP config changed while reading')",
  "    return strict_json_loads(b''.join(chunks).decode('utf-8')), legacy_fingerprint(after)",
  "def close_legacy_config_descriptors(descriptor, parent_descriptor):",
  "    close_managed_projection_descriptors(descriptor, parent_descriptor)",
  "def load_legacy_config_for_update(path, create_parent=False):",
  "    unsafe_parent_prefix = 'legacy MCP config parent is unsafe'",
  "    try:",
  "        parent_descriptor, parent_identity, _ = open_managed_parent(path, create_parent, unsafe_parent_prefix)",
  "    except FileNotFoundError:",
  "        return {}, None, None, None, None",
  "    entry_name = path.name",
  "    flags = os.O_RDONLY | os.O_CLOEXEC | os.O_NONBLOCK | os.O_NOFOLLOW",
  "    try:",
  "        try:",
  "            descriptor = os.open(entry_name, flags, dir_fd=parent_descriptor)",
  "        except FileNotFoundError:",
  "            assert_managed_source_stable(entry_name, parent_descriptor, None)",
  "            assert_managed_parent_stable(path, parent_identity, unsafe_parent_prefix)",
  "            return {}, None, None, parent_descriptor, parent_identity",
  "        try:",
  "            data, identity = read_legacy_descriptor(entry_name, parent_descriptor, descriptor)",
  "            assert_managed_parent_stable(path, parent_identity, unsafe_parent_prefix)",
  "            return data, identity, descriptor, parent_descriptor, parent_identity",
  "        except Exception:",
  "            os.close(descriptor)",
  "            raise",
  "    except Exception:",
  "        os.close(parent_descriptor)",
  "        raise",
  "def read_legacy_config(path):",
  "    data, identity, descriptor, parent_descriptor, _ = load_legacy_config_for_update(path)",
  "    try:",
  "        if descriptor is None:",
  "            raise FileNotFoundError(path)",
  "        return data, identity",
  "    finally:",
  "        close_legacy_config_descriptors(descriptor, parent_descriptor)",
  "def assert_legacy_source_stable(path, identity, descriptor, parent_descriptor, parent_identity):",
  "    if parent_descriptor is None or parent_identity is None:",
  "        raise ValueError('legacy MCP config parent descriptor is unavailable')",
  "    assert_managed_parent_stable(path, parent_identity, 'legacy MCP config parent is unsafe')",
  "    assert_managed_source_stable(path.name, parent_descriptor, identity)",
  "    if identity is None:",
  "        if descriptor is not None:",
  "            raise ValueError('unexpected legacy MCP config descriptor')",
  "        return",
  "    if descriptor is None or validate_legacy_descriptor_path(path.name, parent_descriptor, descriptor) != identity:",
  "        raise ValueError('legacy MCP config changed before mutation')",
  "def legacy_config_bytes(value):",
  "    payload = (json.dumps(value, indent=2, sort_keys=True) + '\\n').encode('utf-8')",
  "    if not payload or len(payload) > LEGACY_MCP_MAX_BYTES:",
  "        raise ValueError('legacy MCP config has invalid rendered size')",
  "    return payload",
  "def create_legacy_config_temp(parent_descriptor):",
  "    flags = os.O_RDWR | os.O_CREAT | os.O_EXCL | os.O_CLOEXEC | os.O_NOFOLLOW",
  "    for _ in range(16):",
  "        name = '.nemoclaw-mcp.' + os.urandom(16).hex()",
  "        try:",
  "            return os.open(name, flags, 0o600, dir_fd=parent_descriptor), name",
  "        except FileExistsError:",
  "            pass",
  "    raise FileExistsError('could not allocate legacy MCP config temporary file')",
  "def write_legacy_config(path, value, identity, descriptor, parent_descriptor, parent_identity):",
  "    assert_legacy_source_stable(path, identity, descriptor, parent_descriptor, parent_identity)",
  "    payload = legacy_config_bytes(value)",
  "    tmp_fd, tmp_name = create_legacy_config_temp(parent_descriptor)",
  "    try:",
  "        offset = 0",
  "        while offset < len(payload):",
  "            written = os.write(tmp_fd, payload[offset:])",
  "            if written <= 0:",
  "                raise OSError('legacy MCP config write made no progress')",
  "            offset += written",
  "        os.fsync(tmp_fd)",
  "        os.close(tmp_fd)",
  "        tmp_fd = None",
  "        assert_legacy_source_stable(path, identity, descriptor, parent_descriptor, parent_identity)",
  "        if identity is None:",
  "            try:",
  "                os.link(tmp_name, path.name, src_dir_fd=parent_descriptor, dst_dir_fd=parent_descriptor, follow_symlinks=False)",
  "            except FileExistsError as exc:",
  "                raise ValueError('legacy MCP config appeared during publication') from exc",
  "            os.unlink(tmp_name, dir_fd=parent_descriptor)",
  "        else:",
  "            os.replace(tmp_name, path.name, src_dir_fd=parent_descriptor, dst_dir_fd=parent_descriptor)",
  "        assert_managed_parent_stable(path, parent_identity, 'legacy MCP config parent is unsafe')",
  "        verification = os.open(path.name, os.O_RDONLY | os.O_CLOEXEC | os.O_NONBLOCK | os.O_NOFOLLOW, dir_fd=parent_descriptor)",
  "        try:",
  "            persisted, _ = read_legacy_descriptor(path.name, parent_descriptor, verification)",
  "        finally:",
  "            os.close(verification)",
  "        assert_managed_parent_stable(path, parent_identity, 'legacy MCP config parent is unsafe')",
  "        return persisted",
  "    finally:",
  "        if tmp_fd is not None:",
  "            os.close(tmp_fd)",
  "        try:",
  "            os.unlink(tmp_name, dir_fd=parent_descriptor)",
  "        except FileNotFoundError:",
  "            pass",
  "def remove_legacy_config(path, identity, descriptor, parent_descriptor, parent_identity):",
  "    assert_legacy_source_stable(path, identity, descriptor, parent_descriptor, parent_identity)",
  "    os.unlink(path.name, dir_fd=parent_descriptor)",
  "    try:",
  "        os.stat(path.name, dir_fd=parent_descriptor, follow_symlinks=False)",
  "    except FileNotFoundError:",
  "        pass",
  "    else:",
  "        raise ValueError('legacy MCP config removal verification failed')",
  "    assert_managed_parent_stable(path, parent_identity, 'legacy MCP config parent is unsafe')",
];
