// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const BASE_APT_SECURITY_FUNCTIONS = [
  [
    "dpkg() {",
    '  if [[ "$#" -eq 1 && "$1" == "--print-architecture" ]]; then',
    '    printf "arm64\\n"',
    '  elif [[ "$#" -eq 4 && "$1" == "-i" && "${2##*/}" == "libexpat1.deb" && "${3##*/}" == "libjq1.deb" && "${4##*/}" == "jq.deb" ]]; then',
    '    [[ -f "$2" && -f "$3" && -f "$4" ]]',
    "  else",
    "    return 64",
    "  fi",
    "}",
  ].join("\n"),
  [
    "dpkg-query() {",
    '  [[ "$#" -eq 3 && "$1" == "-W" && "$2" == \'-f=${Version}\' ]] || return 64',
    '  case "$3" in',
    '    libexpat1) printf "2.8.2-1" ;;',
    '    libjq1|jq) printf "1.8.2-1" ;;',
    '    perl) printf "5.40.1-6" ;;',
    "    *) return 64 ;;",
    "  esac",
    "}",
  ].join("\n"),
  [
    "curl() {",
    '  [[ "$#" -eq 16 && "$1" == "--proto" && "$2" == "=https" && "$3" == "--tlsv1.2" && "$4" == "-fsSL" ]] || return 64',
    '  [[ "$5" == "--retry" && "$6" == "5" && "$7" == "--retry-all-errors" && "$8" == "--retry-delay" && "$9" == "2" ]] || return 64',
    '  [[ "${10}" == "--connect-timeout" && "${11}" == "15" && "${12}" == "--max-time" && "${13}" == "120" && "${14}" == "-o" ]] || return 64',
    '  case "${16}" in',
    '    */e/expat/libexpat1_2.8.2-1_arm64.deb) [[ "${15##*/}" == "libexpat1.deb" ]] ;;',
    '    */j/jq/libjq1_1.8.2-1_arm64.deb) [[ "${15##*/}" == "libjq1.deb" ]] ;;',
    '    */j/jq/jq_1.8.2-1_arm64.deb) [[ "${15##*/}" == "jq.deb" ]] ;;',
    "    *) return 64 ;;",
    "  esac",
    '  printf "%s\\n" "${16}" > "${15}"',
    "}",
  ].join("\n"),
  [
    "sha256sum() {",
    '  [[ "$#" -eq 2 && "$1" == "-c" && "$2" == "-" ]] || return 64',
    "  local line path count=0",
    "  while IFS= read -r line; do",
    '    path="${line#*  }"',
    '    [[ -f "$path" ]] || return 1',
    '    case "$line" in',
    '      "df928e3a8e4da79408d4b18e8cd80a03dffa90130d0698e50041aab5e14f9397  "*/libexpat1.deb) ;;',
    '      "eae4a828df2eb53d728f88109d9f9549e0983a90b573cf0c7fa1e4bbc7533a7e  "*/libjq1.deb) ;;',
    '      "c25086443abd04d1457cbb322a0837f9ba986f82b28f44670467c8dc9be1f696  "*/jq.deb) ;;',
    "      *) return 1 ;;",
    "    esac",
    "    (( count += 1 ))",
    "  done",
    '  [[ "$count" -eq 3 ]]',
    "}",
  ].join("\n"),
  [
    "jq() {",
    '  if [[ "$#" -eq 1 && "$1" == "--version" ]]; then',
    '    printf "jq-1.8.2\\n"',
    '  elif [[ "$#" -eq 2 && "$1" == "-e" && "$2" == \'.sandbox == "healthy"\' ]]; then',
    "    local input",
    "    IFS= read -r input",
    '    [[ "$input" == \'{"sandbox":"healthy"}\' ]]',
    "  else",
    "    return 64",
    "  fi",
    "}",
  ].join("\n"),
  [
    "python3() {",
    '  [[ "$#" -eq 2 && "$1" == "-c" && "$2" == "import pyexpat; assert pyexpat.EXPAT_VERSION == \'expat_2.8.2\', pyexpat.EXPAT_VERSION" ]]',
    "}",
  ].join("\n"),
];
