# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Build the complete immutable runtime inventory consumed by native MSI sealing."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import stat

HEADER = "NEMOCLAW_RUNTIME_CONTENT_V1"
MAX_ENTRIES = 1_000_000
MAX_MANIFEST_BYTES = 256 * 1024 * 1024
RESERVED = {
    "con",
    "prn",
    "aux",
    "nul",
    *("com" + str(i) for i in range(1, 10)),
    *("lpt" + str(i) for i in range(1, 10)),
}


def validate_relative(value: str):
    if not value or len(value.encode("utf-8")) > 8192 or "\\" in value:
        raise ValueError("Invalid runtime manifest relative path.")
    for part in value.split("/"):
        if (
            not part
            or part in {".", ".."}
            or part[-1:] in {" ", "."}
            or any(ord(ch) < 32 or ch in '<>:"|?*' for ch in part)
            or part.split(".")[0].lower() in RESERVED
        ):
            raise ValueError("A runtime manifest path is ambiguous on Windows.")
    if value.casefold() in {"runtime.manifest", "runtime.ready", "runtime.retired"}:
        raise ValueError(
            "Runtime control files are generated by the installer, not supplied as content."
        )


def hash_file(path: Path):
    before = path.lstat()
    if (
        not stat.S_ISREG(before.st_mode)
        or getattr(before, "st_file_attributes", 0) & 0x400
    ):
        raise ValueError("Runtime source files must be regular and nonredirected.")
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while block := stream.read(1024 * 1024):
            digest.update(block)
        after = os.fstat(stream.fileno())
    if (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns) != (
        after.st_dev,
        after.st_ino,
        after.st_size,
        after.st_mtime_ns,
    ):
        raise ValueError("A runtime input changed while it was being inventoried.")
    return before.st_size, digest.hexdigest()


def build(
    root: Path, node: Path, source_revision: str, node_version: str, runtime_id: str
):
    if not re.fullmatch("[a-f0-9]{64}", runtime_id):
        raise ValueError(
            "The runtime namespace must be assigned before final metadata relocation."
        )
    if not re.fullmatch("[a-f0-9]{40}", source_revision) or not re.fullmatch(
        r"(?:0|[1-9][0-9]{0,4})\.(?:0|[1-9][0-9]{0,4})\.(?:0|[1-9][0-9]{0,4})",
        node_version,
    ):
        raise ValueError("The runtime source and shared Node version must be exact.")
    if (
        root.is_symlink()
        or not root.is_dir()
        or getattr(root.lstat(), "st_file_attributes", 0) & 0x400
    ):
        raise ValueError("Runtime content must be an owned, nonredirected directory.")
    _node_size, node_hash = hash_file(node)
    records = []
    names = set()
    for directory, subdirectories, files in os.walk(root, followlinks=False):
        for name in sorted(subdirectories + files):
            path = Path(directory) / name
            relative = path.relative_to(root).as_posix()
            validate_relative(relative)
            key = relative.casefold()
            if key in names:
                raise ValueError("The runtime contains case-colliding Windows paths.")
            names.add(key)
            info = path.lstat()
            if path.is_symlink() or getattr(info, "st_file_attributes", 0) & 0x400:
                raise ValueError("The runtime contains redirected content.")
            encoded = relative.encode("utf-8").hex()
            if stat.S_ISDIR(info.st_mode):
                records.append((relative, "D\t-\t0\t" + encoded))
            else:
                size, digest = hash_file(path)
                records.append(
                    (relative, "F\t" + digest + "\t" + str(size) + "\t" + encoded)
                )
            if len(records) > MAX_ENTRIES:
                raise ValueError("The runtime inventory exceeds its entry bound.")
    if not records or not any(record.startswith("F\t") for _, record in records):
        raise ValueError("The immutable runtime must contain production files.")
    records.sort(key=lambda item: item[0].encode("utf-8"))
    lines = [
        HEADER,
        runtime_id,
        source_revision,
        node_hash,
        node_version,
        str(len(records)),
        *(record for _, record in records),
    ]
    encoded = ("\n".join(lines) + "\n").encode("ascii")
    if len(encoded) > MAX_MANIFEST_BYTES:
        raise ValueError("The runtime inventory exceeds its byte bound.")
    digest = hashlib.sha256(encoded).hexdigest()
    return encoded, {
        "runtimeId": runtime_id,
        "manifestSha256": digest,
        "sourceRevision": source_revision,
        "nodeSha256": node_hash,
        "nodeVersion": node_version,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime-content-root", type=Path, required=True)
    parser.add_argument("--shared-node", type=Path, required=True)
    parser.add_argument("--source-revision", required=True)
    parser.add_argument("--node-version", required=True)
    parser.add_argument("--runtime-id", required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--identity", type=Path, required=True)
    parser.add_argument("--ready-descriptor", type=Path, required=True)
    args = parser.parse_args()
    outputs = [args.manifest, args.identity, args.ready_descriptor]
    if len({path.resolve() for path in outputs}) != len(outputs) or any(
        path.exists() for path in outputs
    ):
        raise ValueError("Manifest outputs must be fresh and distinct.")
    encoded, identity = build(
        args.runtime_content_root,
        args.shared_node,
        args.source_revision,
        args.node_version,
        args.runtime_id,
    )
    args.manifest.write_bytes(encoded)
    args.identity.write_text(json.dumps(identity, indent=2) + "\n", encoding="utf-8")
    # This version-local descriptor is MSI content. Global admission remains
    # retired/blocked until the native verifier seals the complete tuple.
    fields = [
        "NEMOCLAW_RUNTIME_V1",
        *(
            identity[name]
            for name in (
                "runtimeId",
                "manifestSha256",
                "sourceRevision",
                "nodeSha256",
                "nodeVersion",
            )
        ),
    ]
    args.ready_descriptor.write_bytes(("\n".join(fields) + "\n").encode("ascii"))


if __name__ == "__main__":
    main()
