{{- if not .Values.inference.existingSecret }}
{{- if .Values.inference.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nemoclaw-cpu.secretName" . }}
  namespace: {{ include "nemoclaw-cpu.namespace" . }}
  labels:
    {{- include "nemoclaw-cpu.labels" . | nindent 4 }}
type: Opaque
stringData:
  NVIDIA_INFERENCE_HUB_API_KEY: {{ .Values.inference.apiKey | quote }}
{{- end }}
{{- end }}
