apiVersion: v1
kind: Service
metadata:
  name: {{ include "nemoclaw-cpu.fullname" . }}-agent
  namespace: {{ include "nemoclaw-cpu.namespace" . }}
  labels:
    {{- include "nemoclaw-cpu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nemoclaw-cpu.selectorLabels" . | nindent 4 }}
