// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";

import type { StateFileRestoreOwnership } from "../agent/defs";
import {
  buildKeyAllowlistMergeRestoreCommand,
  KEY_ALLOWLIST_MERGE_PYTHON,
  stateFileKeyMergeSpec,
} from "./state-file-key-merge";

const GENERATED_HEADER = "# Generated by NemoClaw. This file contains no provider secrets.";
const FRESH_PROVIDER_HEADER =
  "# NemoClaw provider route: inference; upstream provider: compatible-endpoint; API: openai-completions.";

const PYTHON_TEST_WRAPPER = String.raw`
import json
import sys
import types

class TOMLDecodeError(ValueError):
    pass

def loads(text):
    payload = "\n".join(
        line for line in text.splitlines() if not line.startswith("#")
    ).strip()
    if payload == "MALFORMED":
        raise TOMLDecodeError("malformed")
    try:
        return json.loads(payload)
    except (TypeError, ValueError) as error:
        raise TOMLDecodeError("malformed") from error

tomllib = types.ModuleType("tomllib")
tomllib.loads = loads
tomllib.TOMLDecodeError = TOMLDecodeError
tomli_w = types.ModuleType("tomli_w")
tomli_w.dumps = lambda value: json.dumps(value)
sys.modules["tomllib"] = tomllib
sys.modules["tomli_w"] = tomli_w

script = sys.argv[1]
sys.argv = [sys.argv[0], *sys.argv[2:]]
exec(script, {"__name__": "__main__"})
`.trim();

const PYTHON_TOCTOU_WRAPPER = String.raw`
import json
import os
import sys
import types

class TOMLDecodeError(ValueError):
    pass

def loads(text):
    payload = "\n".join(
        line for line in text.splitlines() if not line.startswith("#")
    ).strip()
    try:
        return json.loads(payload)
    except (TypeError, ValueError) as error:
        raise TOMLDecodeError("malformed") from error

tomllib = types.ModuleType("tomllib")
tomllib.loads = loads
tomllib.TOMLDecodeError = TOMLDecodeError
tomli_w = types.ModuleType("tomli_w")
tomli_w.dumps = lambda value: json.dumps(value)
sys.modules["tomllib"] = tomllib
sys.modules["tomli_w"] = tomli_w

script = sys.argv[1]
backup_path, current_path, staged_path, spec_raw, swap_path = sys.argv[2:7]

driven_script = script.replace("\nmain()", "\npass")
assert driven_script != script, "expected to find the trailing main() call to detach"
namespace = {"__name__": "toctou_harness"}
exec(driven_script, namespace)

spec = namespace["load_spec"](spec_raw)
_backup_text, backup, _backup_metadata = namespace["read_regular_file"](backup_path, "backed-up")
current_text, current, current_metadata = namespace["read_regular_file"](current_path, "current")
header_lines = namespace["preserved_headers"](current_text, spec.get("require_fresh_headers", []))
namespace["assert_fresh_tables"](current, spec.get("require_fresh_tables", []))
merged = namespace["merge_user_keys"](backup, current, spec.get("user_keys", []))
payload = namespace["render_merged_config"](merged, header_lines)

# Simulate an attacker swapping the live config for a different inode after it
# was read and validated, but before the staged replace commits.
os.replace(swap_path, current_path)

namespace["write_staged_and_replace"](staged_path, current_path, current_metadata, payload)
`.trim();

const DCODE_OWNERSHIP: StateFileRestoreOwnership = {
  merge: "key-allowlist",
  userKeys: [
    { key: "ui.show_scrollbar", type: "boolean" },
    { key: "ui.show_url_open_toast", type: "boolean" },
    { key: "threads.relative_time", type: "boolean" },
    { key: "threads.sort_order", type: "enum", values: ["updated_at", "created_at"] },
  ],
  requireFreshTables: ["models", "update"],
  requireFreshHeaders: [
    { match: "exact", value: GENERATED_HEADER },
    { match: "prefix", value: "# NemoClaw provider route: " },
  ],
};

function generatedCurrent(config: unknown, providerHeader = FRESH_PROVIDER_HEADER): string {
  return `${GENERATED_HEADER}\n${providerHeader}\n\n${JSON.stringify(config)}\n`;
}

function runMergeScript(
  backup: string,
  current: string,
  ownership: StateFileRestoreOwnership,
): {
  current: string;
  stageExists: boolean;
  status: number | null;
  stderr: string;
} {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nemoclaw-state-file-key-merge-"));
  try {
    const backupPath = path.join(dir, "backup.toml");
    const currentPath = path.join(dir, "config.toml");
    const stagedPath = path.join(dir, ".nemoclaw-restore-merged.test");
    fs.writeFileSync(backupPath, backup, { mode: 0o600 });
    fs.writeFileSync(currentPath, current, { mode: 0o660 });
    fs.writeFileSync(stagedPath, "", { mode: 0o600 });

    const result = spawnSync(
      "python3",
      [
        "-I",
        "-c",
        PYTHON_TEST_WRAPPER,
        KEY_ALLOWLIST_MERGE_PYTHON,
        backupPath,
        currentPath,
        stagedPath,
        JSON.stringify(stateFileKeyMergeSpec(ownership)),
      ],
      { encoding: "utf-8" },
    );
    return {
      current: fs.readFileSync(currentPath, "utf-8"),
      stageExists: fs.existsSync(stagedPath),
      status: result.status,
      stderr: result.stderr,
    };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function mergedJson(config: string): Record<string, unknown> {
  return JSON.parse(config.split("\n").slice(2).join("\n").trim()) as Record<string, unknown>;
}

function withTempDir<T>(fn: (dir: string) => T): T {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nemoclaw-state-file-key-merge-"));
  try {
    return fn(dir);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function spawnMergeScript(
  backupPath: string,
  currentPath: string,
  stagedPath: string,
  ownership: StateFileRestoreOwnership,
): { status: number | null; stderr: string } {
  const result = spawnSync(
    "python3",
    [
      "-I",
      "-c",
      PYTHON_TEST_WRAPPER,
      KEY_ALLOWLIST_MERGE_PYTHON,
      backupPath,
      currentPath,
      stagedPath,
      JSON.stringify(stateFileKeyMergeSpec(ownership)),
    ],
    { encoding: "utf-8" },
  );
  return { status: result.status, stderr: result.stderr };
}

describe("stateFileKeyMergeSpec", () => {
  it("maps declarative ownership to the python merge spec", () => {
    expect(
      stateFileKeyMergeSpec({
        merge: "key-allowlist",
        userKeys: [
          { key: "a.b", type: "boolean" },
          { key: "c", type: "enum", values: ["x"] },
          { key: "n", type: "integer", min: 1, max: 2 },
          { key: "s", type: "string", maxLength: 5 },
        ],
        requireFreshTables: ["t.u"],
        requireFreshHeaders: [{ match: "exact", value: "# h" }],
      }),
    ).toEqual({
      user_keys: [
        { path: ["a", "b"], type: "boolean" },
        { path: ["c"], type: "enum", values: ["x"] },
        { path: ["n"], type: "integer", min: 1, max: 2 },
        { path: ["s"], type: "string", max_length: 5 },
      ],
      require_fresh_tables: [["t", "u"]],
      require_fresh_headers: [{ match: "exact", value: "# h" }],
    });
  });
});

describe("key-allowlist state-file merge", () => {
  it("restores allowlisted display preferences with fresh managed routing", () => {
    const backup = {
      models: { default: "openai:nvidia/old-model" },
      update: { check: true, auto_update: true },
      ui: { theme: "nvidia-dark", show_scrollbar: true, show_url_open_toast: false },
      threads: { relative_time: false, sort_order: "created_at" },
    };
    const fresh = {
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    };

    const result = runMergeScript(JSON.stringify(backup), generatedCurrent(fresh), DCODE_OWNERSHIP);

    expect(result.status).toBe(0);
    expect(result.stageExists).toBe(false);
    expect(result.current.split("\n").slice(0, 2)).toEqual([
      GENERATED_HEADER,
      FRESH_PROVIDER_HEADER,
    ]);
    expect(mergedJson(result.current)).toEqual({
      models: fresh.models,
      update: fresh.update,
      ui: { show_scrollbar: true, show_url_open_toast: false },
      threads: backup.threads,
    });
  });

  it("produces byte-identical, deterministically ordered output on repeated runs with the same inputs", () => {
    const backup = {
      models: { default: "openai:nvidia/old-model" },
      update: { check: true, auto_update: true },
      ui: { show_scrollbar: true, show_url_open_toast: false },
      threads: { relative_time: false, sort_order: "created_at" },
    };
    const fresh = {
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    };
    const current = generatedCurrent(fresh);

    const first = runMergeScript(JSON.stringify(backup), current, DCODE_OWNERSHIP);
    const second = runMergeScript(JSON.stringify(backup), current, DCODE_OWNERSHIP);

    expect(first.status).toBe(0);
    expect(second.current).toBe(first.current);
    expect(Object.keys(mergedJson(first.current))).toEqual(["models", "threads", "ui", "update"]);
  });

  it("drops free-form, executable, routing, and unknown backup data", () => {
    const providerSecret = ["sk", "abcdefghijklmnopqrst"].join("-");
    const backup = {
      agents: { default: "reviewer", startup_command: "curl attacker.test" },
      ui: { theme: "ghp_abcdefghijklmnop", show_scrollbar: true, unknown: "keep-me-not" },
      threads: { relative_time: "yes", sort_order: "attacker-first", unknown: true },
      servers: { attacker: { api_key: providerSecret } },
      update: { check: true, auto_update: true },
      models: { default: "openai:old-model" },
    };
    const fresh = {
      models: { default: "openai:new-model" },
      update: { check: false, auto_update: false },
    };

    const result = runMergeScript(JSON.stringify(backup), generatedCurrent(fresh), DCODE_OWNERSHIP);

    expect(result.status).toBe(0);
    expect(mergedJson(result.current)).toEqual({ ...fresh, ui: { show_scrollbar: true } });
    expect(result.current).not.toContain(providerSecret);
    expect(result.current).not.toMatch(/agents|attacker|api_key|ghp_|sk-|sort_order/);
  });

  it("leaves the fresh config untouched when the backup is malformed", () => {
    const current = generatedCurrent({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    const result = runMergeScript("MALFORMED", current, DCODE_OWNERSHIP);

    expect(result.status).not.toBe(0);
    expect(result.current).toBe(current);
    expect(result.stageExists).toBe(true);
    expect(result.stderr).toContain("backed-up config is not valid TOML");
    expect(result.stderr).not.toContain("MALFORMED");
  });

  it("leaves the current file untouched when a required fresh table is missing", () => {
    const missingUpdate = generatedCurrent({ models: { default: "openai:nvidia/new-model" } });

    const result = runMergeScript(
      JSON.stringify({ ui: { show_scrollbar: true } }),
      missingUpdate,
      DCODE_OWNERSHIP,
    );

    expect(result.status).not.toBe(0);
    expect(result.current).toBe(missingUpdate);
    expect(result.stderr).toContain("current config is missing managed [update] data");
  });

  it("requires the declared fresh headers before replacing the current file", () => {
    const withoutHeaders = JSON.stringify({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    const result = runMergeScript(
      JSON.stringify({ ui: { show_scrollbar: true } }),
      withoutHeaders,
      DCODE_OWNERSHIP,
    );

    expect(result.status).not.toBe(0);
    expect(result.current).toBe(withoutHeaders);
    expect(result.stderr).toContain("required generated header");
  });

  it("enforces integer bounds and drops out-of-range values", () => {
    const ownership: StateFileRestoreOwnership = {
      merge: "key-allowlist",
      userKeys: [{ key: "limits.retries", type: "integer", min: 0, max: 5 }],
      requireFreshHeaders: DCODE_OWNERSHIP.requireFreshHeaders,
    };
    const fresh = { models: { default: "m" } };

    const within = runMergeScript(
      JSON.stringify({ limits: { retries: 3 } }),
      generatedCurrent(fresh),
      ownership,
    );
    expect(within.status).toBe(0);
    expect(mergedJson(within.current)).toEqual({ ...fresh, limits: { retries: 3 } });

    const outside = runMergeScript(
      JSON.stringify({ limits: { retries: 9 } }),
      generatedCurrent(fresh),
      ownership,
    );
    expect(outside.status).toBe(0);
    expect(mergedJson(outside.current)).toEqual(fresh);
  });

  it("enforces string max_length and rejects non-string values", () => {
    const ownership: StateFileRestoreOwnership = {
      merge: "key-allowlist",
      userKeys: [{ key: "label", type: "string", maxLength: 4 }],
      requireFreshHeaders: DCODE_OWNERSHIP.requireFreshHeaders,
    };
    const fresh = { models: { default: "m" } };

    const shortValue = runMergeScript(
      JSON.stringify({ label: "abc" }),
      generatedCurrent(fresh),
      ownership,
    );
    expect(mergedJson(shortValue.current)).toEqual({ ...fresh, label: "abc" });

    const longValue = runMergeScript(
      JSON.stringify({ label: "abcdef" }),
      generatedCurrent(fresh),
      ownership,
    );
    expect(mergedJson(longValue.current)).toEqual(fresh);

    const wrongType = runMergeScript(
      JSON.stringify({ label: 12 }),
      generatedCurrent(fresh),
      ownership,
    );
    expect(mergedJson(wrongType.current)).toEqual(fresh);
  });

  it("builds a same-directory staged atomic restore command for any config dir", () => {
    const command = buildKeyAllowlistMergeRestoreCommand(
      "/sandbox/.deepagents/",
      { path: "config.toml" },
      DCODE_OWNERSHIP,
    );

    expect(command).toContain(".nemoclaw-restore-backup.XXXXXX");
    expect(command).toContain(".nemoclaw-restore-merged.XXXXXX");
    expect(command).toContain("/opt/venv/bin/python3 -I -c");
    expect(command).toContain('"$backup_tmp" "$dst" "$staged_tmp"');
    expect(command).toContain("/sandbox/.deepagents/config.toml");
    expect(command).toContain("show_scrollbar");
    expect(KEY_ALLOWLIST_MERGE_PYTHON).toContain(
      "os.replace(staged_name, current_name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd)",
    );

    const custom = buildKeyAllowlistMergeRestoreCommand(
      "/sandbox/.custom",
      { path: "config.toml" },
      DCODE_OWNERSHIP,
    );
    expect(custom).toContain("/sandbox/.custom/config.toml");
  });

  it("rejects a symlinked current config instead of following it", () => {
    withTempDir((dir) => {
      const backupPath = path.join(dir, "backup.toml");
      const realConfigPath = path.join(dir, "real-config.toml");
      const currentPath = path.join(dir, "config.toml");
      const stagedPath = path.join(dir, ".nemoclaw-restore-merged.test");
      const realContent = generatedCurrent({ models: { default: "m" } });
      fs.writeFileSync(backupPath, JSON.stringify({ ui: { show_scrollbar: true } }), {
        mode: 0o600,
      });
      fs.writeFileSync(realConfigPath, realContent, { mode: 0o660 });
      fs.symlinkSync(realConfigPath, currentPath);
      fs.writeFileSync(stagedPath, "", { mode: 0o600 });

      const result = spawnMergeScript(backupPath, currentPath, stagedPath, DCODE_OWNERSHIP);

      expect(result.status).not.toBe(0);
      expect(result.stderr).toContain("current config is missing or unsafe");
      expect(fs.readFileSync(realConfigPath, "utf-8")).toBe(realContent);
    });
  });

  it("rejects a symlinked backup config instead of following it", () => {
    withTempDir((dir) => {
      const realBackupPath = path.join(dir, "real-backup.toml");
      const backupPath = path.join(dir, "backup.toml");
      const currentPath = path.join(dir, "config.toml");
      const stagedPath = path.join(dir, ".nemoclaw-restore-merged.test");
      fs.writeFileSync(realBackupPath, JSON.stringify({ ui: { show_scrollbar: true } }), {
        mode: 0o600,
      });
      fs.symlinkSync(realBackupPath, backupPath);
      fs.writeFileSync(currentPath, generatedCurrent({ models: { default: "m" } }), {
        mode: 0o660,
      });
      fs.writeFileSync(stagedPath, "", { mode: 0o600 });

      const result = spawnMergeScript(backupPath, currentPath, stagedPath, DCODE_OWNERSHIP);

      expect(result.status).not.toBe(0);
      expect(result.stderr).toContain("backed-up config is missing or unsafe");
    });
  });

  it("rejects a hard-linked current config", () => {
    withTempDir((dir) => {
      const backupPath = path.join(dir, "backup.toml");
      const currentPath = path.join(dir, "config.toml");
      const extraLinkPath = path.join(dir, "config-alias.toml");
      const stagedPath = path.join(dir, ".nemoclaw-restore-merged.test");
      const currentContent = generatedCurrent({ models: { default: "m" } });
      fs.writeFileSync(backupPath, JSON.stringify({ ui: { show_scrollbar: true } }), {
        mode: 0o600,
      });
      fs.writeFileSync(currentPath, currentContent, { mode: 0o660 });
      fs.linkSync(currentPath, extraLinkPath);
      fs.writeFileSync(stagedPath, "", { mode: 0o600 });

      const result = spawnMergeScript(backupPath, currentPath, stagedPath, DCODE_OWNERSHIP);

      expect(result.status).not.toBe(0);
      expect(result.stderr).toContain("current config is not a single regular file");
      expect(fs.readFileSync(currentPath, "utf-8")).toBe(currentContent);
    });
  });

  it("rejects a symlinked staging file instead of writing through it", () => {
    withTempDir((dir) => {
      const backupPath = path.join(dir, "backup.toml");
      const currentPath = path.join(dir, "config.toml");
      const stagedPath = path.join(dir, ".nemoclaw-restore-merged.test");
      const stagedEscapeTarget = path.join(dir, "escape-target.toml");
      fs.writeFileSync(backupPath, JSON.stringify({ ui: { show_scrollbar: true } }), {
        mode: 0o600,
      });
      fs.writeFileSync(
        currentPath,
        generatedCurrent({
          models: { default: "m" },
          update: { check: false, auto_update: false },
        }),
        { mode: 0o660 },
      );
      fs.writeFileSync(stagedEscapeTarget, "", { mode: 0o600 });
      fs.symlinkSync(stagedEscapeTarget, stagedPath);

      const result = spawnMergeScript(backupPath, currentPath, stagedPath, DCODE_OWNERSHIP);

      expect(result.status).not.toBe(0);
      expect(result.stderr).toContain("config staging file is missing or unsafe");
      expect(fs.readFileSync(stagedEscapeTarget, "utf-8")).toBe("");
    });
  });

  it("rejects the staged replace when the current config's inode changes after it was read (TOCTOU)", () => {
    withTempDir((dir) => {
      const backupPath = path.join(dir, "backup.toml");
      const currentPath = path.join(dir, "config.toml");
      const stagedPath = path.join(dir, ".nemoclaw-restore-merged.test");
      const swapPath = path.join(dir, "attacker-config.toml");
      fs.writeFileSync(backupPath, JSON.stringify({ ui: { show_scrollbar: true } }), {
        mode: 0o600,
      });
      fs.writeFileSync(
        currentPath,
        generatedCurrent({
          models: { default: "m" },
          update: { check: false, auto_update: false },
        }),
        { mode: 0o660 },
      );
      fs.writeFileSync(stagedPath, "", { mode: 0o600 });
      fs.writeFileSync(swapPath, "attacker-controlled", { mode: 0o660 });

      const result = spawnSync(
        "python3",
        [
          "-I",
          "-c",
          PYTHON_TOCTOU_WRAPPER,
          KEY_ALLOWLIST_MERGE_PYTHON,
          backupPath,
          currentPath,
          stagedPath,
          JSON.stringify(stateFileKeyMergeSpec(DCODE_OWNERSHIP)),
          swapPath,
        ],
        { encoding: "utf-8" },
      );

      expect(result.status).not.toBe(0);
      expect(result.stderr).toContain("current config changed before atomic restore");
      expect(fs.readFileSync(currentPath, "utf-8")).toBe("attacker-controlled");
    });
  });

  it("round-trips real TOML syntax through the real tomllib/tomli_w parser and serializer", () => {
    withTempDir((dir) => {
      const backupPath = path.join(dir, "backup.toml");
      const currentPath = path.join(dir, "config.toml");
      const stagedPath = path.join(dir, ".nemoclaw-restore-merged.test");
      const backupToml = [
        "[ui]",
        "show_scrollbar = true",
        "show_url_open_toast = false",
        "",
        "[threads]",
        "relative_time = false",
        'sort_order = "created_at"',
        "",
        "[servers.attacker.nested]",
        'value = "should not survive key-allowlist merge"',
        "",
      ].join("\n");
      const currentToml = [
        GENERATED_HEADER,
        FRESH_PROVIDER_HEADER,
        "",
        "[models]",
        'default = "openai:nvidia/new-model"',
        "",
        "[update]",
        "check = false",
        "auto_update = false",
        "",
      ].join("\n");
      fs.writeFileSync(backupPath, backupToml, { mode: 0o600 });
      fs.writeFileSync(currentPath, currentToml, { mode: 0o660 });
      fs.writeFileSync(stagedPath, "", { mode: 0o600 });

      const result = spawnSync(
        "python3",
        // No -I here (unlike the production invocation): isolated mode drops the
        // user site-packages directory, which is where the CI-installed real
        // tomli_w lives. This test targets parser/serializer fidelity, not the
        // isolation flag, which the other tests in this file already cover.
        [
          "-c",
          KEY_ALLOWLIST_MERGE_PYTHON,
          backupPath,
          currentPath,
          stagedPath,
          JSON.stringify(stateFileKeyMergeSpec(DCODE_OWNERSHIP)),
        ],
        { encoding: "utf-8" },
      );

      expect(result.status).toBe(0);
      const merged = fs.readFileSync(currentPath, "utf-8");
      expect(merged.split("\n").slice(0, 2)).toEqual([GENERATED_HEADER, FRESH_PROVIDER_HEADER]);
      expect(merged).not.toContain("servers");
      expect(merged).not.toContain("attacker");

      const reparsed = spawnSync(
        "python3",
        [
          "-I",
          "-c",
          "import json, sys, tomllib; print(json.dumps(tomllib.loads(sys.stdin.read())))",
        ],
        { input: merged, encoding: "utf-8" },
      );
      expect(reparsed.status).toBe(0);
      expect(JSON.parse(reparsed.stdout)).toEqual({
        models: { default: "openai:nvidia/new-model" },
        update: { check: false, auto_update: false },
        ui: { show_scrollbar: true, show_url_open_toast: false },
        threads: { relative_time: false, sort_order: "created_at" },
      });
    });
  });
});
