// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { parse, stringify } from "smol-toml";
import { describe, expect, it } from "vitest";

import type { StateFileKeyAllowlistRestoreOwnership } from "../agent/defs";
import { shellQuote } from "../runner";
import {
  buildKeyAllowlistMergeRestoreCommand,
  KEY_ALLOWLIST_MERGE_PYTHON,
  stateFileKeyMergeSpec,
} from "./state-file-key-merge";

const GENERATED_HEADER = "# Generated by NemoClaw. This file contains no provider secrets.";
const FRESH_PROVIDER_HEADER =
  "# NemoClaw provider route: inference; upstream provider: compatible-endpoint; API: openai-completions.";

const PYTHON_TEST_TOMLI_WRITER_SHIM = String.raw`
import json
import subprocess
import sys
import types

NODE_TOML_WRITER = r"""
const fs = require("node:fs");
const { stringify } = require("smol-toml");
const value = JSON.parse(fs.readFileSync(0, "utf8"));
process.stdout.write(stringify(value));
"""

def dumps(value):
    completed = subprocess.run(
        ["node", "-e", NODE_TOML_WRITER],
        input=json.dumps(value, allow_nan=False),
        capture_output=True,
        check=True,
        text=True,
    )
    return completed.stdout

tomli_w = types.ModuleType("tomli_w")
tomli_w.dumps = dumps
sys.modules["tomli_w"] = tomli_w

try:
    script_index = sys.argv.index("-c", 1) + 1
except ValueError:
    script_index = 1
script = sys.argv[script_index]
sys.argv = [sys.argv[0], *sys.argv[script_index + 1:]]
exec(script, {"__name__": "__main__"})
`.trim();

const INODE_SWAP_MARKER = "# replacement created during race test\n";
const INODE_REVALIDATION_POINT = String.raw`        try:
            latest_current = os.stat(current_name, dir_fd=parent_fd, follow_symlinks=False)`;
const INODE_SWAP_SCRIPT = KEY_ALLOWLIST_MERGE_PYTHON.replace(
  INODE_REVALIDATION_POINT,
  String.raw`        swapped_name = current_name + ".pre-swap"
        os.replace(current_name, swapped_name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd)
        replacement_fd = os.open(
            current_name,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o660,
            dir_fd=parent_fd,
        )
        try:
            os.write(replacement_fd, b"# replacement created during race test\n")
            os.fsync(replacement_fd)
        finally:
            os.close(replacement_fd)

        try:
            latest_current = os.stat(current_name, dir_fd=parent_fd, follow_symlinks=False)`,
);

if (INODE_SWAP_SCRIPT === KEY_ALLOWLIST_MERGE_PYTHON) {
  throw new Error("Could not instrument the current-config inode revalidation point");
}

const IN_PLACE_MUTATION_SCRIPT = KEY_ALLOWLIST_MERGE_PYTHON.replace(
  INODE_REVALIDATION_POINT,
  String.raw`        mutation_fd = os.open(
            current_name,
            os.O_WRONLY | getattr(os, "O_NOFOLLOW", 0),
            dir_fd=parent_fd,
        )
        try:
            os.lseek(mutation_fd, 0, os.SEEK_END)
            os.write(mutation_fd, b"# concurrent mutation\n")
            os.fsync(mutation_fd)
        finally:
            os.close(mutation_fd)

        try:
            latest_current = os.stat(current_name, dir_fd=parent_fd, follow_symlinks=False)`,
);

if (IN_PLACE_MUTATION_SCRIPT === KEY_ALLOWLIST_MERGE_PYTHON) {
  throw new Error("Could not instrument the current-config version revalidation point");
}

const STAGE_REVALIDATION_POINT = String.raw`        try:
            latest_staged = os.stat(staged_name, dir_fd=parent_fd, follow_symlinks=False)`;

function stageSwapScript(kind: "hardlink" | "regular" | "symlink"): string {
  const replacement =
    kind === "symlink"
      ? "os.symlink(attack_name, staged_name, dir_fd=parent_fd)"
      : kind === "hardlink"
        ? "os.link(attack_name, staged_name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd, follow_symlinks=False)"
        : String.raw`replacement_fd = os.open(
            staged_name,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o600,
            dir_fd=parent_fd,
        )
        try:
            os.write(replacement_fd, b"replacement stage must not be installed\n")
            os.fsync(replacement_fd)
        finally:
            os.close(replacement_fd)`;
  const instrumented = KEY_ALLOWLIST_MERGE_PYTHON.replace(
    STAGE_REVALIDATION_POINT,
    String.raw`        attack_name = ".nemoclaw-stage-attack-target"
        attack_fd = os.open(
            attack_name,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o600,
            dir_fd=parent_fd,
        )
        try:
            os.write(attack_fd, b"stage attack target must remain unchanged\n")
            os.fsync(attack_fd)
        finally:
            os.close(attack_fd)
        os.unlink(staged_name, dir_fd=parent_fd)
        ${replacement}

        try:
            latest_staged = os.stat(staged_name, dir_fd=parent_fd, follow_symlinks=False)`,
  );
  if (instrumented === KEY_ALLOWLIST_MERGE_PYTHON) {
    throw new Error("Could not instrument the staged-config inode revalidation point");
  }
  return instrumented;
}

const DCODE_OWNERSHIP: StateFileKeyAllowlistRestoreOwnership = {
  merge: "key-allowlist",
  userKeys: [
    { key: "ui.show_scrollbar", type: "boolean" },
    { key: "ui.show_url_open_toast", type: "boolean" },
    { key: "threads.relative_time", type: "boolean" },
    { key: "threads.sort_order", type: "enum", values: ["updated_at", "created_at"] },
  ],
  requireFreshTables: ["models", "update"],
  requireFreshHeaders: [
    { match: "exact", value: GENERATED_HEADER },
    { match: "prefix", value: "# NemoClaw provider route: " },
  ],
};

function generatedCurrent(config: unknown, providerHeader = FRESH_PROVIDER_HEADER): string {
  return `${GENERATED_HEADER}\n${providerHeader}\n\n${stringify(config)}`;
}

interface RunMergeOptions {
  script?: string;
}

function runMergeScript(
  backup: string,
  current: string,
  ownership: StateFileKeyAllowlistRestoreOwnership,
  options: RunMergeOptions = {},
): {
  current: string;
  status: number | null;
  stderr: string;
  stageEntries: string[];
  swappedOriginal: string | null;
} {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nemoclaw-state-file-key-merge-"));
  try {
    const currentPath = path.join(dir, "config.toml");
    fs.writeFileSync(currentPath, current, { mode: 0o660 });

    const result = spawnSync(
      "python3",
      [
        "-I",
        "-c",
        PYTHON_TEST_TOMLI_WRITER_SHIM,
        options.script ?? KEY_ALLOWLIST_MERGE_PYTHON,
        dir,
        "config.toml",
        JSON.stringify(stateFileKeyMergeSpec(ownership)),
      ],
      { encoding: "utf-8", input: backup },
    );
    return {
      current: fs.readFileSync(currentPath, "utf-8"),
      status: result.status,
      stderr: result.stderr,
      stageEntries: fs
        .readdirSync(dir)
        .filter((entry) => entry.startsWith(".nemoclaw-restore-merged.")),
      swappedOriginal: fs.existsSync(`${currentPath}.pre-swap`)
        ? fs.readFileSync(`${currentPath}.pre-swap`, "utf-8")
        : null,
    };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

interface ProductionRunOptions {
  currentLink?: "hardlink" | "symlink";
  parentAncestorSymlink?: boolean;
  script?: string;
}

function runProductionCommand(
  backup: string,
  current: string,
  options: ProductionRunOptions = {},
): {
  command: string;
  attackTarget: string | null;
  current: string;
  currentTarget: string | null;
  dir: string;
  entries: string[];
  status: number | null;
  stderr: string;
} {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nemoclaw-state-file-command-"));
  let configDir = dir;
  let stateFilePath = "config.toml";
  if (options.parentAncestorSymlink) {
    fs.mkdirSync(path.join(dir, "real", "nested"), { recursive: true });
    fs.symlinkSync("real", path.join(dir, "alias"));
    configDir = path.join(dir, "alias", "nested");
    stateFilePath = "alias/nested/config.toml";
  }
  const currentPath = path.join(configDir, "config.toml");
  let currentTargetPath: string | null = null;
  try {
    if (options.currentLink) {
      currentTargetPath = path.join(dir, "current.target");
      fs.writeFileSync(currentTargetPath, current, { mode: 0o660 });
      if (options.currentLink === "symlink") {
        fs.symlinkSync(path.basename(currentTargetPath), currentPath);
      } else {
        fs.linkSync(currentTargetPath, currentPath);
      }
    } else {
      fs.writeFileSync(currentPath, current, { mode: 0o660 });
    }
    let command = buildKeyAllowlistMergeRestoreCommand(
      dir,
      { path: stateFilePath },
      DCODE_OWNERSHIP,
    );
    if (options.script) {
      command = command.replace(shellQuote(KEY_ALLOWLIST_MERGE_PYTHON), shellQuote(options.script));
    }
    command = command.replace(
      "/opt/venv/bin/python3",
      `python3 -I -c ${shellQuote(PYTHON_TEST_TOMLI_WRITER_SHIM)}`,
    );
    const result = spawnSync("bash", ["-c", command], {
      encoding: "utf-8",
      input: backup,
    });
    return {
      command,
      attackTarget: fs.existsSync(path.join(dir, ".nemoclaw-stage-attack-target"))
        ? fs.readFileSync(path.join(dir, ".nemoclaw-stage-attack-target"), "utf-8")
        : null,
      current: fs.readFileSync(currentPath, "utf-8"),
      currentTarget: currentTargetPath ? fs.readFileSync(currentTargetPath, "utf-8") : null,
      dir,
      entries: fs.readdirSync(dir),
      status: result.status,
      stderr: result.stderr,
    };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

function mergedToml(config: string): Record<string, unknown> {
  return parse(config) as Record<string, unknown>;
}

describe("stateFileKeyMergeSpec", () => {
  it("maps declarative ownership to the python merge spec", () => {
    expect(
      stateFileKeyMergeSpec({
        merge: "key-allowlist",
        userKeys: [
          { key: "a.b", type: "boolean" },
          { key: "c", type: "enum", values: ["x"] },
          { key: "n", type: "integer", min: 1, max: 2 },
          { key: "s", type: "string", maxLength: 5 },
        ],
        requireFreshTables: ["t.u"],
        requireFreshHeaders: [{ match: "exact", value: "# h" }],
      }),
    ).toEqual({
      user_keys: [
        { path: ["a", "b"], type: "boolean" },
        { path: ["c"], type: "enum", values: ["x"] },
        { path: ["n"], type: "integer", min: 1, max: 2 },
        { path: ["s"], type: "string", max_length: 5 },
      ],
      require_fresh_tables: [["t", "u"]],
      require_fresh_headers: [{ match: "exact", value: "# h" }],
    });
  });
});

describe("key-allowlist state-file merge", () => {
  it("restores allowlisted display preferences with fresh managed routing", () => {
    const backup = {
      models: { default: "openai:nvidia/old-model" },
      update: { check: true, auto_update: true },
      ui: { theme: "nvidia-dark", show_scrollbar: true, show_url_open_toast: false },
      threads: { relative_time: false, sort_order: "created_at" },
    };
    const fresh = {
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    };

    const result = runMergeScript(stringify(backup), generatedCurrent(fresh), DCODE_OWNERSHIP);

    expect(result.status).toBe(0);
    expect(result.stageEntries).toEqual([]);
    expect(result.current.split("\n").slice(0, 2)).toEqual([
      GENERATED_HEADER,
      FRESH_PROVIDER_HEADER,
    ]);
    expect(result.current).toContain("[models]");
    expect(mergedToml(result.current)).toEqual({
      models: fresh.models,
      update: fresh.update,
      ui: { show_scrollbar: true, show_url_open_toast: false },
      threads: backup.threads,
    });
  });

  it("produces byte-identical, deterministically ordered output on repeated runs with the same inputs", () => {
    const backup = {
      models: { default: "openai:nvidia/old-model" },
      update: { check: true, auto_update: true },
      ui: { show_scrollbar: true, show_url_open_toast: false },
      threads: { relative_time: false, sort_order: "created_at" },
    };
    const fresh = {
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    };
    const current = generatedCurrent(fresh);

    const first = runMergeScript(stringify(backup), current, DCODE_OWNERSHIP);
    const second = runMergeScript(stringify(backup), current, DCODE_OWNERSHIP);

    expect(first.status).toBe(0);
    expect(second.current).toBe(first.current);
    expect(Object.keys(mergedToml(first.current))).toEqual(["models", "threads", "ui", "update"]);
  });

  it("drops free-form, executable, routing, and unknown backup data", () => {
    const providerSecret = ["sk", "abcdefghijklmnopqrst"].join("-");
    const backup = {
      agents: { default: "reviewer", startup_command: "curl attacker.test" },
      ui: { theme: "ghp_abcdefghijklmnop", show_scrollbar: true, unknown: "keep-me-not" },
      threads: { relative_time: "yes", sort_order: "attacker-first", unknown: true },
      servers: { attacker: { api_key: providerSecret } },
      update: { check: true, auto_update: true },
      models: { default: "openai:old-model" },
    };
    const fresh = {
      models: { default: "openai:new-model" },
      update: { check: false, auto_update: false },
    };

    const result = runMergeScript(stringify(backup), generatedCurrent(fresh), DCODE_OWNERSHIP);

    expect(result.status).toBe(0);
    expect(mergedToml(result.current)).toEqual({ ...fresh, ui: { show_scrollbar: true } });
    expect(result.current).not.toContain(providerSecret);
    expect(result.current).not.toMatch(/agents|attacker|api_key|ghp_|sk-|sort_order/);
  });

  it("leaves the fresh config untouched when the backup is malformed", () => {
    const current = generatedCurrent({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    const malformed = "[ui\nshow_scrollbar = true\n";
    const result = runMergeScript(malformed, current, DCODE_OWNERSHIP);

    expect(result.status).not.toBe(0);
    expect(result.current).toBe(current);
    expect(result.stageEntries).toEqual([]);
    expect(result.stderr).toContain("backed-up config is not valid TOML");
    expect(result.stderr).not.toContain(malformed);
  });

  it("leaves the current file untouched when a required fresh table is missing", () => {
    const missingUpdate = generatedCurrent({ models: { default: "openai:nvidia/new-model" } });

    const result = runMergeScript(
      stringify({ ui: { show_scrollbar: true } }),
      missingUpdate,
      DCODE_OWNERSHIP,
    );

    expect(result.status).not.toBe(0);
    expect(result.current).toBe(missingUpdate);
    expect(result.stderr).toContain("current config is missing managed [update] data");
  });

  it("requires the declared fresh headers before replacing the current file", () => {
    const withoutHeaders = stringify({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    const result = runMergeScript(
      stringify({ ui: { show_scrollbar: true } }),
      withoutHeaders,
      DCODE_OWNERSHIP,
    );

    expect(result.status).not.toBe(0);
    expect(result.current).toBe(withoutHeaders);
    expect(result.stderr).toContain("required generated header");
  });

  it("enforces integer bounds and drops out-of-range values", () => {
    const ownership: StateFileKeyAllowlistRestoreOwnership = {
      merge: "key-allowlist",
      userKeys: [{ key: "limits.retries", type: "integer", min: 0, max: 5 }],
      requireFreshHeaders: DCODE_OWNERSHIP.requireFreshHeaders,
    };
    const fresh = { models: { default: "m" } };

    const within = runMergeScript(
      stringify({ limits: { retries: 3 } }),
      generatedCurrent(fresh),
      ownership,
    );
    expect(within.status).toBe(0);
    expect(mergedToml(within.current)).toEqual({ ...fresh, limits: { retries: 3 } });

    const outside = runMergeScript(
      stringify({ limits: { retries: 9 } }),
      generatedCurrent(fresh),
      ownership,
    );
    expect(outside.status).toBe(0);
    expect(mergedToml(outside.current)).toEqual(fresh);
  });

  it("enforces string max_length and rejects non-string values", () => {
    const ownership: StateFileKeyAllowlistRestoreOwnership = {
      merge: "key-allowlist",
      userKeys: [{ key: "label", type: "string", maxLength: 4 }],
      requireFreshHeaders: DCODE_OWNERSHIP.requireFreshHeaders,
    };
    const fresh = { models: { default: "m" } };

    const shortValue = runMergeScript(
      stringify({ label: "abc" }),
      generatedCurrent(fresh),
      ownership,
    );
    expect(mergedToml(shortValue.current)).toEqual({ ...fresh, label: "abc" });

    const longValue = runMergeScript(
      stringify({ label: "abcdef" }),
      generatedCurrent(fresh),
      ownership,
    );
    expect(mergedToml(longValue.current)).toEqual(fresh);

    const wrongType = runMergeScript(stringify({ label: 12 }), generatedCurrent(fresh), ownership);
    expect(mergedToml(wrongType.current)).toEqual(fresh);
  });

  it("keeps a fresh scalar when an old nested preference no longer has a table parent", () => {
    const ownership: StateFileKeyAllowlistRestoreOwnership = {
      merge: "key-allowlist",
      userKeys: [{ key: "ui.show_scrollbar", type: "boolean" }],
      requireFreshHeaders: DCODE_OWNERSHIP.requireFreshHeaders,
    };
    const fresh = { ui: "managed-by-current-version" };

    const result = runMergeScript(
      stringify({ ui: { show_scrollbar: true } }),
      generatedCurrent(fresh),
      ownership,
    );

    expect(result.status).toBe(0);
    expect(mergedToml(result.current)).toEqual(fresh);
  });

  it("preserves every safe leading comment after validating managed headers", () => {
    const fresh = {
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    };
    const extraHeader = "# Image generation: current";
    const current = `${GENERATED_HEADER}\n${FRESH_PROVIDER_HEADER}\n${extraHeader}\n\n${stringify(fresh)}`;

    const result = runMergeScript(
      stringify({ ui: { show_scrollbar: true } }),
      current,
      DCODE_OWNERSHIP,
    );

    expect(result.status).toBe(0);
    expect(result.current.split("\n").slice(0, 3)).toEqual([
      GENERATED_HEADER,
      FRESH_PROVIDER_HEADER,
      extraHeader,
    ]);
  });

  it("rejects unsafe metadata in an extra leading comment", () => {
    const fresh = {
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    };
    const current = `${GENERATED_HEADER}\n${FRESH_PROVIDER_HEADER}\n# unsafe\tmetadata\n\n${stringify(fresh)}`;

    const result = runMergeScript(stringify({}), current, DCODE_OWNERSHIP);

    expect(result.status).not.toBe(0);
    expect(result.current).toBe(current);
    expect(result.stderr).toContain("unsafe generated header metadata");
  });

  it("executes the full production command with backup TOML only on stdin", () => {
    const backup = stringify({ ui: { show_scrollbar: true } });
    const current = generatedCurrent({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    const result = runProductionCommand(backup, current);

    expect(result.status).toBe(0);
    expect(mergedToml(result.current)).toEqual({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
      ui: { show_scrollbar: true },
    });
    expect(result.command).not.toContain("backup_tmp");
    expect(result.command).not.toContain("staged_tmp");
    expect(result.command).not.toContain('cat > "$backup_tmp"');
    expect(result.entries.some((entry) => entry.startsWith(".nemoclaw-restore-merged."))).toBe(
      false,
    );
  });

  it("rejects symlinked and hard-linked current configs through the production command", () => {
    const backup = stringify({ ui: { show_scrollbar: true } });
    const current = generatedCurrent({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    for (const currentLink of ["symlink", "hardlink"] as const) {
      const result = runProductionCommand(backup, current, { currentLink });

      expect(result.status, currentLink).not.toBe(0);
      expect(result.current, currentLink).toBe(current);
      expect(result.currentTarget, currentLink).toBe(current);
    }
  });

  it("rejects a symlink in a config parent ancestor through the production command", () => {
    const backup = stringify({ ui: { show_scrollbar: true } });
    const current = generatedCurrent({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    const result = runProductionCommand(backup, current, { parentAncestorSymlink: true });

    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("config parent directory is unsafe");
    expect(result.current).toBe(current);
  });

  it("rejects symlink, hardlink, and inode swaps of its private stage before replacement", () => {
    const backup = stringify({ ui: { show_scrollbar: true } });
    const current = generatedCurrent({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    for (const kind of ["symlink", "hardlink", "regular"] as const) {
      const result = runProductionCommand(backup, current, { script: stageSwapScript(kind) });

      expect(result.status, kind).not.toBe(0);
      expect(result.stderr, kind).toContain("config staging file changed before atomic restore");
      expect(result.current, kind).toBe(current);
      expect(result.attackTarget, kind).toBe("stage attack target must remain unchanged\n");
      expect(
        result.entries.some((entry) => entry.startsWith(".nemoclaw-restore-merged.")),
        kind,
      ).toBe(true);
    }
  });

  it("refuses to replace a current config whose inode changes after validation", () => {
    const current = generatedCurrent({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    const result = runMergeScript(
      stringify({ ui: { show_scrollbar: true } }),
      current,
      DCODE_OWNERSHIP,
      { script: INODE_SWAP_SCRIPT },
    );

    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("current config changed before atomic restore");
    expect(result.current).toBe(INODE_SWAP_MARKER);
    expect(result.swappedOriginal).toBe(current);
    expect(result.stageEntries).toEqual([]);
  });

  it("refuses to replace a current config modified in place after validation", () => {
    const current = generatedCurrent({
      models: { default: "openai:nvidia/new-model" },
      update: { check: false, auto_update: false },
    });

    const result = runMergeScript(
      stringify({ ui: { show_scrollbar: true } }),
      current,
      DCODE_OWNERSHIP,
      { script: IN_PLACE_MUTATION_SCRIPT },
    );

    expect(result.status).not.toBe(0);
    expect(result.stderr).toContain("current config changed before atomic restore");
    expect(result.current).toBe(`${current}# concurrent mutation\n`);
    expect(result.stageEntries).toEqual([]);
  });

  it("builds a same-directory staged atomic restore command for any config dir", () => {
    const command = buildKeyAllowlistMergeRestoreCommand(
      "/sandbox/.deepagents/",
      { path: "config.toml" },
      DCODE_OWNERSHIP,
    );

    expect(command).toContain("/opt/venv/bin/python3 -I -c");
    expect(command).toContain('"$dst"');
    expect(command).not.toContain("mktemp");
    expect(command).not.toContain('chmod 600 "$');
    expect(command).toContain("/sandbox/.deepagents/config.toml");
    expect(command).toContain("show_scrollbar");
    expect(KEY_ALLOWLIST_MERGE_PYTHON).toContain(
      "os.replace(staged_name, current_name, src_dir_fd=parent_fd, dst_dir_fd=parent_fd)",
    );

    const custom = buildKeyAllowlistMergeRestoreCommand(
      "/sandbox/.custom",
      { path: "config.toml" },
      DCODE_OWNERSHIP,
    );
    expect(custom).toContain("/sandbox/.custom/config.toml");
  });
});
